/**
 * Simple RPG Demo — full GameDev monorepo pipeline.
 *
 * Assets generated by: gameassets batch (Text2D → Text3D → Paint3D → Rigging3D)
 * Animation:           animator3d breathe-idle + walk → embedded clips in hero.glb
 * Handoff to public/:  gameassets handoff --public-dir public
 * Sky equirect:        skymap2d generate → public/assets/sky/sky.png
 * Audio:               text2sound → public/assets/audio/
 *
 * GLBs are loaded declaratively via <gltf-load> in index.html.
 * The hero model is loaded imperatively here, animated via GltfAnimator,
 * and synced to the player entity every frame.
 */
import {
  applyEquirectSkyEnvironment,
  configure,
  defineQuery,
  getScene,
  GltfAnimator,
  isKeyDown,
  loadGltfAnimated,
  Parent,
  Player,
  Renderer,
  run,
  type State,
  WorldTransform,
} from 'vibegame';
import { Box3, Clock } from 'three';

const CLIP_IDLE = 'Animator3D_BreatheIdle';
const CLIP_WALK = 'Animator3D_Walk';
const MOVE_KEYS = [
  'KeyW',
  'KeyA',
  'KeyS',
  'KeyD',
  'ArrowUp',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
];

const playerQuery = defineQuery([Player]);
const parentQuery = defineQuery([Parent]);

interface HeroHandle {
  animator: GltfAnimator;
  yOffset: number;
}

async function loadHero(state: State): Promise<HeroHandle> {
  const gltf = await loadGltfAnimated(state, '/assets/models/hero.glb');
  gltf.scene.name = 'hero-player-model';

  const box = new Box3().setFromObject(gltf.scene);
  const yOffset = -box.min.y;

  const animator = new GltfAnimator(gltf, { crossfadeDuration: 0.2 });
  animator.play(CLIP_IDLE);

  console.log(
    '[simple-rpg] Hero loaded with clips:',
    animator.clipNames.join(', ')
  );
  return { animator, yOffset };
}

function hideBoxCharacterParts(
  state: ReturnType<Awaited<ReturnType<typeof run>>['getState']>
) {
  const world = state.world;
  const players = playerQuery(world);
  if (players.length === 0) return;
  const playerEid = players[0];

  const allParented = parentQuery(world);
  const childrenOfPlayer = allParented.filter(
    (e: number) => Parent.entity[e] === playerEid
  );

  for (const child of childrenOfPlayer) {
    const grandchildren = allParented.filter(
      (e: number) => Parent.entity[e] === child
    );
    for (const gc of grandchildren) {
      if (state.hasComponent(gc, Renderer)) {
        Renderer.visible[gc] = 0;
      }
    }
  }
}

function startGameLoop(
  hero: HeroHandle,
  state: ReturnType<Awaited<ReturnType<typeof run>>['getState']>
) {
  const clock = new Clock();

  function tick() {
    const dt = clock.getDelta();

    const isMoving = MOVE_KEYS.some((k) => isKeyDown(k));
    const wantClip = isMoving ? CLIP_WALK : CLIP_IDLE;
    if (hero.animator.activeClipName !== wantClip) {
      hero.animator.play(wantClip);
    }
    hero.animator.update(dt);

    const players = playerQuery(state.world);
    if (players.length > 0) {
      const eid = players[0];
      const root = hero.animator.root;
      root.position.set(
        WorldTransform.posX[eid],
        WorldTransform.posY[eid] + hero.yOffset,
        WorldTransform.posZ[eid]
      );
      root.quaternion.set(
        WorldTransform.rotX[eid],
        WorldTransform.rotY[eid],
        WorldTransform.rotZ[eid],
        WorldTransform.rotW[eid]
      );
    }

    requestAnimationFrame(tick);
  }

  tick();
}

async function bootstrap(): Promise<void> {
  configure({ canvas: '#game-canvas' });
  const runtime = await run();
  const state = runtime.getState();

  try {
    await applyEquirectSkyEnvironment(state, '/assets/sky/sky.png');
  } catch {
    console.warn('[simple-rpg] Sky env map not loaded (optional).');
  }

  if (getScene(state)) {
    try {
      const hero = await loadHero(state);
      hideBoxCharacterParts(state);
      startGameLoop(hero, state);
    } catch (err) {
      console.warn(
        '[simple-rpg] Hero model not found, using box character.',
        err
      );
    }
  }
}

void bootstrap();
