// Viber terrain chunk material — 4 simultaneous ground layers per chunk.
//
// Each terrain chunk carries its OWN material: the four pool textures with
// the highest aggregate weight in that chunk + one RGBA8 splat plane baked
// per chunk (weights renormalized to sum 1). Areas of the world can render
// completely different layer sets.
//
// WORLD SPECIALIZATION: `viber run` rewrites the CONFIG block below from the
// `<Terrain>` spec before the renderer loads this file.
//
// BINDINGS — the material is **bindless** (`TerrainChunkMaterial`), and it
// has to be: a non-bindless custom material with a single texture binding
// segfaults the NVIDIA driver inside `vkCreatePipelineLayout`. So the
// textures live in the shared arrays of `bevy_render::bindless` and this
// shader only carries INDICES into them, read from the index table at
// binding 0. The `#else` branch is the portable non-bindless layout (used
// on any device where bevy turns bindless off).

#import bevy_pbr::forward_io::{VertexOutput, FragmentOutput}
#import bevy_pbr::mesh_view_bindings::view
// `apply_fog(view_bindings::fog, …)` referencia o NAMESPACE — sem este
// alias o compose falha com ImportNotFound("view_bindings") e o material
// perde o pipeline (nenhum chunk desenha; só o clear-color aparece no
// lugar do chão).
#import bevy_pbr::mesh_view_bindings as view_bindings
#import bevy_pbr::pbr_functions::apply_fog

#ifdef BINDLESS
#import bevy_render::bindless::{bindless_textures_2d, bindless_samplers_filtering}
#import bevy_pbr::mesh_bindings::mesh
#endif  // BINDLESS

// === WORLD CONFIG (generated by `viber run` — edit the XML, not this block) ===
const CFG_TRI_SLOPE: f32 = 0.5;
const CFG_TRI_SOFT: f32 = 0.12;
const CFG_STRATA_SPACING: f32 = 4;
const CFG_STRATA_STRENGTH: f32 = 0.25;
const CFG_ROCK_DARKEN: f32 = 0.45;
const CFG_STREAK: f32 = 0.5;
const CFG_MOSS: f32 = 0.35;
// === END WORLD CONFIG ===

// Per-chunk layer table. `tiles[i].x` is the tile size in meters of layer i,
// `tints/flats/roughs` its color correction, flat far color and perceptual
// roughness; `chunk` places the plane: xy = origin XZ, z = edge size,
// w = index (0..3) of the rock layer for the triplanar walls, -1 = off.
// `day_tint.rgb` multiplies the final albedo (day/night cycle);
// `sun_dir.xyz` is the sun TRAVEL direction (where the light goes — the
// same sun the shadows follow, published with the day-tint steps).
struct TerrainChunkParams {
    tiles: array<vec4<f32>, 4>,
    tints: array<vec4<f32>, 4>,
    flats: array<vec4<f32>, 4>,
    roughs: array<vec4<f32>, 4>,
    chunk: vec4<f32>,
    day_tint: vec4<f32>,
    sun_dir: vec4<f32>,
};

#ifdef BINDLESS

// Bindless index table — one entry per material slot; the field order is the
// bindless-index order declared by `TerrainChunkMaterial`
// (`#[data(0, …)]` then the five texture/sampler pairs at 1..10).
struct TerrainChunkBindings {
    material: u32,        // 0
    layer0_texture: u32,  // 1
    layer0_sampler: u32,  // 2
    layer1_texture: u32,  // 3
    layer1_sampler: u32,  // 4
    layer2_texture: u32,  // 5
    layer2_sampler: u32,  // 6
    layer3_texture: u32,  // 7
    layer3_sampler: u32,  // 8
    splat_texture: u32,   // 9
    splat_sampler: u32,   // 10
}

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<storage> material_indices: array<TerrainChunkBindings>;
@group(#{MATERIAL_BIND_GROUP}) @binding(10) var<storage> params_array: array<TerrainChunkParams>;

#else   // BINDLESS

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> params_direct: TerrainChunkParams;
@group(#{MATERIAL_BIND_GROUP}) @binding(1) var layer0: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(2) var layer0_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(3) var layer1: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(4) var layer1_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(5) var layer2: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(6) var layer2_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(7) var layer3: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(8) var layer3_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(9) var splat: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(10) var splat_sampler: sampler;

#endif  // BINDLESS

// Achatamento por distância: perto vê-se o material, longe vê-se cor. FLAT_MIN
// é o achatamento mínimo colado à câmara — as fotos do pool têm contraste a
// mais para um mundo cel-ish mesmo aos pés do herói.
const FLAT_NEAR: f32 = 42.0;
const FLAT_FAR: f32 = 260.0;
const FLAT_MIN: f32 = 0.22;

// Weights below this contribute nothing visible; skipping their texture
// fetch keeps the typical fragment at 2–3 layers instead of 4.
const WEIGHT_EPSILON: f32 = 0.004;

/// The chunk's table. `slot` is the material's index in the bindless slab
/// (always 0 without bindless).
fn chunk_params(slot: u32) -> TerrainChunkParams {
#ifdef BINDLESS
    return params_array[material_indices[slot].material];
#else   // BINDLESS
    return params_direct;
#endif  // BINDLESS
}

/// Layer `i` (0..3) of this chunk. Bindings cannot be indexed without
/// bindless, so the non-bindless path picks by explicit branches; the
/// gradients are always explicit, which is what makes the call legal from
/// the non-uniform per-weight branches below.
fn layer_sample(i: i32, slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec3<f32> {
#ifdef BINDLESS
    let idx = material_indices[slot];
    var tex = idx.layer0_texture;
    var samp = idx.layer0_sampler;
    if (i == 1) {
        tex = idx.layer1_texture;
        samp = idx.layer1_sampler;
    } else if (i == 2) {
        tex = idx.layer2_texture;
        samp = idx.layer2_sampler;
    } else if (i == 3) {
        tex = idx.layer3_texture;
        samp = idx.layer3_sampler;
    }
    return textureSampleGrad(
        bindless_textures_2d[tex],
        bindless_samplers_filtering[samp],
        uv,
        dx,
        dy,
    ).rgb;
#else   // BINDLESS
    if (i == 0) {
        return textureSampleGrad(layer0, layer0_sampler, uv, dx, dy).rgb;
    }
    if (i == 1) {
        return textureSampleGrad(layer1, layer1_sampler, uv, dx, dy).rgb;
    }
    if (i == 2) {
        return textureSampleGrad(layer2, layer2_sampler, uv, dx, dy).rgb;
    }
    return textureSampleGrad(layer3, layer3_sampler, uv, dx, dy).rgb;
#endif  // BINDLESS
}

/// The chunk's splat plane (local 0..1 UVs over the chunk).
fn splat_sample(slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec4<f32> {
#ifdef BINDLESS
    let idx = material_indices[slot];
    return textureSampleGrad(
        bindless_textures_2d[idx.splat_texture],
        bindless_samplers_filtering[idx.splat_sampler],
        uv,
        dx,
        dy,
    );
#else   // BINDLESS
    return textureSampleGrad(splat, splat_sampler, uv, dx, dy);
#endif  // BINDLESS
}

// ── Wall skin (deterministic hash noise — the rock detail needs no extra
// textures or bindings). Value noise in 2 octaves drives the runoff
// streaks and the moss patches.
fn hash21(p: vec2<f32>) -> f32 {
    return fract(sin(dot(p, vec2<f32>(127.1, 311.7))) * 43758.5453);
}
fn vnoise(p: vec2<f32>) -> f32 {
    let i = floor(p);
    let f = fract(p);
    let u = f * f * (3.0 - 2.0 * f);
    let a = mix(hash21(i), hash21(i + vec2<f32>(1.0, 0.0)), u.x);
    let b = mix(hash21(i + vec2<f32>(0.0, 1.0)), hash21(i + vec2<f32>(1.0, 1.0)), u.x);
    return mix(a, b, u.y);
}

@fragment
fn fragment(
    in: VertexOutput,
    @builtin(front_facing) is_front: bool,
) -> FragmentOutput {
#ifdef BINDLESS
    let slot = mesh[in.instance_index].material_and_lightmap_bind_group_slot & 0xffffu;
#else   // BINDLESS
    let slot = 0u;
#endif  // BINDLESS
    let params = chunk_params(slot);

    let world = in.world_position.xyz;
    let normal = select(-in.world_normal, in.world_normal, is_front);

    // Splat coverage of THIS chunk: local 0..1 UVs over the chunk plane. The
    // gradients are taken ONCE here; inside the per-layer branches below every
    // fetch uses textureSampleGrad (explicit gradients are legal in
    // non-uniform control flow).
    let local = (world.xz - params.chunk.xy) / params.chunk.z;
    let ldx = dpdx(local);
    let ldy = dpdy(local);
    let s = splat_sample(slot, local, ldx, ldy);

    // World-space derivative shared by every layer (uv = world / tile).
    let wdx = dpdx(world.xz);
    let wdy = dpdy(world.xz);

    // Achatamento por distância: perto vê-se o material, longe vê-se cor.
    let view_dist = distance(world, view.world_position.xyz);
    let flat_mix = mix(FLAT_MIN, 1.0, smoothstep(FLAT_NEAR, FLAT_FAR, view_dist));

    var albedo = vec3<f32>(0.0);
    var rough = 0.0;

    if (s.r > WEIGHT_EPSILON) {
        let t = params.tiles[0].x;
        let tex = layer_sample(0, slot, world.xz / t, wdx / t, wdy / t);
        albedo += s.r * mix(tex * params.tints[0].rgb, params.flats[0].rgb, flat_mix);
        rough += s.r * params.roughs[0].x;
    }
    if (s.g > WEIGHT_EPSILON) {
        let t = params.tiles[1].x;
        let tex = layer_sample(1, slot, world.xz / t, wdx / t, wdy / t);
        albedo += s.g * mix(tex * params.tints[1].rgb, params.flats[1].rgb, flat_mix);
        rough += s.g * params.roughs[1].x;
    }
    if (s.b > WEIGHT_EPSILON) {
        let t = params.tiles[2].x;
        let tex = layer_sample(2, slot, world.xz / t, wdx / t, wdy / t);
        albedo += s.b * mix(tex * params.tints[2].rgb, params.flats[2].rgb, flat_mix);
        rough += s.b * params.roughs[2].x;
    }
    if (s.a > WEIGHT_EPSILON) {
        let t = params.tiles[3].x;
        let tex = layer_sample(3, slot, world.xz / t, wdx / t, wdy / t);
        albedo += s.a * mix(tex * params.tints[3].rgb, params.flats[3].rgb, flat_mix);
        rough += s.a * params.roughs[3].x;
    }

    // The CPU bakes the four weights to sum 1; clamp anyway so a fallback
    // plane must not push the sum past 1.
    let total = max(s.r + s.g + s.b + s.a, 1.0);
    albedo /= total;
    rough = clamp(rough / total, 0.05, 1.0);

    // ── Cliff walls: triplanar 2-fetch + estratos ─────────────────────────
    //
    // A projeção top-down do splat estica-se nas paredes ("plastilina").
    // Faces mais íngremes que o cliff-angle (`CFG_TRI_SLOPE`; ≥ 1 desliga o
    // caminho, const-folded) trocam o blend splat pela ROCK layer do chunk
    // (a mountain_stone quando o chunk a carregou), com bandas de estratos
    // em world.y a fazerem a parede ler como rocha sedimentar.
    var wall_n = vec3<f32>(0.0, 1.0, 0.0);
    var tri_mix = 0.0;
    if (CFG_TRI_SLOPE < 1.0) {
        // O declive vem da normal INTERPOLADA, não das derivadas de ecrã.
        // `cross(dpdx(world), dpdy(world))` é a normal do TRIÂNGULO: constante
        // dentro dele e descontínua na aresta, por isso o gate saltava de
        // triângulo para triângulo e a encosta enchia-se de manchas de pedra
        // com bordas poligonais retas (o "faixas/manchas nas montanhas"). A
        // normal do vértice vem de `HeightField::sample_normal` com um épsilon
        // constante em todo o terreno: é suave entre triângulos E estável
        // entre LODs, portanto o mesmo pixel não muda de rocha para relva
        // quando o chunk troca de nível.
        let geom_n = normal;
        let slope = 1.0 - abs(geom_n.y);
        // Gate DUPLA: declive × fator de região — o
        // alpha das vertex colors transporta a máscara de cliff FILTRADA
        // (componentes conexos com área/queda/extent mínimos, cozida no
        // mesh builder). Um declive espúrio isolado tem fator 0 e nunca
        // ganha pedra; a borda de região faz blend suave. O canal R
        // transporta o WALL SPACE da máscara (0 = brow, 1 = pé, 0.5
        // neutro): meteorização, AO de contacto e a distribuição de
        // escorrimentos/musgo leem-se dele.
        var region = 1.0;
        var wall = 0.5;
#ifdef VERTEX_COLORS
        region = clamp(in.color.a, 0.0, 1.0);
        wall = clamp(in.color.r, 0.0, 1.0);
#endif
        let tri = smoothstep(CFG_TRI_SLOPE, CFG_TRI_SLOPE + CFG_TRI_SOFT, slope) * region;
        if (tri > 0.001) {
            let rock = i32(params.chunk.w);
            if (rock >= 0) {
                // Só mistura a normal de parede quando o chunk TEM rock —
                // sem ela o bump ficava (0,1,0) e a parede lia iluminada
                // como chão plano (flat/estourada).
                tri_mix = tri;
                let uv_zy = vec2<f32>(world.z, world.y);
                let uv_xy = vec2<f32>(world.x, world.y);
                let dzy_x = dpdx(uv_zy);
                let dzy_y = dpdy(uv_zy);
                let dxy_x = dpdx(uv_xy);
                let dxy_y = dpdy(uv_xy);
                let use_xy = abs(geom_n.x) < abs(geom_n.z);
                let side = select(uv_zy, uv_xy, use_xy);
                let sd = select(dzy_x, dxy_x, use_xy);
                let sy = select(dzy_y, dxy_y, use_xy);
                let t = params.tiles[rock].x;
                let rock_tex = layer_sample(rock, slot, side / t, sd / t, sy / t);
                // Detail normal do LUMINANCE (fallback sem bindings novas):
                // 2 fetches extra na MESMA textura — o gradiente de
                // luminância é o relevo da rocha. Some ao brilho à
                // distância (flat_mix) para não cintilar longe.
                let luma = vec3<f32>(0.299, 0.587, 0.114);
                let bump = 1.1 * (1.0 - flat_mix);
                if (bump > 0.01) {
                    let e = 0.35 / t;
                    let c0 = dot(rock_tex, luma);
                    let cu = dot(layer_sample(rock, slot, side / t + vec2<f32>(e, 0.0), sd / t, sy / t), luma);
                    let cv = dot(layer_sample(rock, slot, side / t + vec2<f32>(0.0, e), sd / t, sy / t), luma);
                    let u_axis = select(vec3<f32>(0.0, 0.0, 1.0), vec3<f32>(1.0, 0.0, 0.0), use_xy);
                    wall_n = normalize(geom_n
                        - (u_axis * (cu - c0) + vec3<f32>(0.0, 1.0, 0.0) * (cv - c0)) * bump);
                }
                let band = world.y / CFG_STRATA_SPACING;
                let band_id = floor(band);
                let hue = fract(sin(band_id * vec3<f32>(12.9898, 78.233, 37.719)) * 43758.5453);
                // Estratos cromáticos: cada banda puxa para um tom próprio
                // (quente ↔ frio) e 1 em 4 bandas é um banco DURO — mais
                // claro, o estrato resistente que sai à frente na erosão.
                let warm = vec3<f32>(
                    1.0 - CFG_STRATA_STRENGTH,
                    1.0 - CFG_STRATA_STRENGTH * 0.75,
                    1.0 - CFG_STRATA_STRENGTH * 0.45,
                );
                let cool = vec3<f32>(
                    1.0 + CFG_STRATA_STRENGTH * 0.45,
                    1.0 + CFG_STRATA_STRENGTH * 0.75,
                    1.0 + CFG_STRATA_STRENGTH,
                );
                let band_tint = mix(warm, cool, hue);
                let band_mod = band_id - floor(band_id * 0.25) * 4.0;
                let hard = step(band_mod, 0.5) * 0.14;
                let line = smoothstep(0.82, 1.0, fract(band)) * CFG_STRATA_STRENGTH * 0.8;
                // ── Fade dos detalhes SUB-PIXEL ────────────────────────────
                // Estratos (4 m), escorrimentos (~4 m) e o bump de luminância
                // são detalhe de PERTO. A 300 m uma banda de 4 m ocupa ~1 px:
                // o passo `floor(world.y / 4)` deixa de ser rocha sedimentar e
                // vira aliasing — riscas horizontais claras/escuras a
                // atravessar a montanha inteira (o "faixas nas montanhas"). O
                // mesmo `flat_mix` que já achata a textura por distância
                // desliga-os: perto nada muda, longe fica a cor plana da
                // camada. Sem isto nenhum mipmap ajuda — a banda é aritmética
                // no fragmento, não um texel.
                let detail = 1.0 - flat_mix;
                // CFG_ROCK_DARKEN: a parede le PEDRA ESCURA mesmo sob
                // paletas claras — os tints por slot existem para o chao a
                // pleno sol (mountain_stone clareia 1.35x); o rochedo
                // devolve o texel a ~45% (o escuro do basalto da referencia).
                var rock_col = rock_tex * params.tints[rock].rgb * CFG_ROCK_DARKEN
                    * mix(vec3<f32>(1.0), band_tint, detail)
                    * (1.0 - line * detail)
                    * (1.0 + hard * detail);
                // Meteorização vertical (wall space): o brow seca ao sol,
                // o pé ganha poeira de detrito; AO de contacto onde a
                // parede encosta no chão; escorrimentos — faixas verticais
                // de água (noise esticado em Y), mais fortes na metade
                // inferior onde a humidade escorre.
                let weather = mix(1.06, 0.88, wall);
                let toe_ao = 1.0 - 0.38 * smoothstep(0.82, 0.98, wall);
                let su = vec2<f32>((world.x + world.z) * 0.22, world.y * 0.06);
                let streak_n = vnoise(su) * 0.65 + vnoise(su * 2.7) * 0.35;
                let streak = 1.0
                    - CFG_STREAK * detail * smoothstep(0.48, 0.88, streak_n) * mix(0.55, 1.0, wall);
                rock_col = rock_col * weather * toe_ao * streak;
                rock_col = mix(rock_col, params.flats[rock].rgb, flat_mix);
                albedo = mix(albedo, rock_col, tri);
                rough = mix(rough, params.roughs[rock].x, tri);
            }
        }
        // Musgo procedural: manchas húmidas nos OMBROS e flancos médios da
        // região de cliff (declive médio — nem o plano da relva, nem a face
        // nua), mais denso perto do pé onde a humidade se acumula. O gate
        // pela `region` impede musgo em colinas longe de qualquer parede.
        // Também desvanece com a distância: as manchas têm ~6 m e ao longe
        // viravam salpicos verdes de 1 px na encosta.
        let moss_n = vnoise(world.xz * 0.17) * 0.6 + vnoise(world.xz * 0.51) * 0.4;
        let moss_band = smoothstep(0.10, 0.20, slope) * (1.0 - smoothstep(0.50, 0.78, slope));
        let moss = CFG_MOSS * region * moss_band * (1.0 - flat_mix)
            * smoothstep(0.50, 0.78, moss_n)
            * mix(0.55, 1.25, wall);
        albedo = mix(albedo, vec3<f32>(0.17, 0.24, 0.08), clamp(moss, 0.0, 0.85));
    }

    // Day/night tint (see `terrain_day_tint`) — the whole ground darkens at
    // night with a warm hand at golden hour.
    albedo *= params.day_tint.rgb;

    // Lighting: sun + ambient, simple on purpose — the value of this
    // material is the GROUND BLEND, not the PBR stack. Nas paredes a
    // normal ganha o detail bump do luminance (pesado por `tri_mix`).
    // O sol vem do uniform (o mesmo passo quantizado do day_tint segue a
    // luz real da cena) — hardcoded nunca batia certo com as sombras dos
    // props nem com a hora dourada do céu.
    let n = normalize(mix(normal, wall_n, clamp(tri_mix, 0.0, 1.0)));
    let sun_travel = select(
        normalize(vec3<f32>(0.35, -0.8, -0.45)),
        normalize(params.sun_dir.xyz),
        params.sun_dir.w > 0.0,
    );
    let sun_amount = max(dot(n, -sun_travel), 0.0);
    let lit = albedo * (0.45 + 0.55 * sun_amount);

    var out: FragmentOutput;
    var color = vec4<f32>(lit, 1.0);
#ifdef DISTANCE_FOG
    // Fog da câmara (`DistanceFog`): o PBR standard aplica-a DENTRO do
    // shader do material — sem este bloco o terreno por layers lia o
    // horizonte a 100% de contraste, as transições de LOD ao longe ficavam
    // duras e o pop-in de chunks era visível. A ordem é a do
    // `main_pass_post_lighting_processing`: fog antes do tone mapping.
    color = apply_fog(
        view_bindings::fog,
        color,
        world,
        view.world_position.xyz,
        in.position.xy,
    );
#endif
    out.color = color;
    return out;
}
