//! Animated water material — a WGSL [`MaterialExtension`] on top of
//! [`StandardMaterial`] (`ExtendedMaterial`) for the lake/river mirrors built
//! by [`super::water`].
//!
//! Same architecture as [`crate::sky`] (read the ARCHITECTURE NOTE there): the
//! Bevy 0.19 slot-1 storage promotion never re-uploads custom material
//! uniforms, so the per-world config (day clock for the glint, `<Weather>`
//! wind for the wave field) is injected as **consts** — `viber run` rewrites
//! the CONFIG block of `shaders/water.wgsl` before the renderer loads it — and
//! per-frame values come from the engine's `Globals` binding.
//!
//! The base `StandardMaterial` still carries the static surface properties
//! (vertex colors: body color + shore fade alpha; `AlphaMode::Blend`;
//! reflectance), while the extension fragment adds the life: wave normals,
//! Fresnel alpha (see-through from above, mirror at grazing angles), a sky
//! tint at grazing angles and a sun/moon glint as emissive. Lighting, shadows
//! and fog remain the stock PBR path.

use bevy::asset::Asset;
use bevy::pbr::{ExtendedMaterial, MaterialExtension, StandardMaterial};
use bevy::prelude::*;
use bevy::reflect::TypePath;
use bevy::render::render_resource::AsBindGroup;
use bevy::shader::ShaderRef;

/// Template WGSL da água (defaults; `viber run` reescreve o bloco CONFIG com
/// os valores do mundo antes de o renderer o carregar).
pub const WATER_WGSL: &str = include_str!("water.wgsl");

const CONFIG_BEGIN: &str = "// === WORLD CONFIG";
const CONFIG_END: &str = "// === END WORLD CONFIG ===";

/// Water surface = `StandardMaterial` + the animated-water extension.
pub type WaterMaterial = ExtendedMaterial<StandardMaterial, WaterExtension>;

/// Extension sem bindings — tudo chega por consts especializadas no WGSL e
/// pelo binding `Globals` da engine (mesma razão do [`crate::sky`]).
#[derive(Debug, Clone, Asset, TypePath, AsBindGroup)]
pub struct WaterExtension {}

impl MaterialExtension for WaterExtension {
    fn fragment_shader() -> ShaderRef {
        "shaders/water.wgsl".into()
    }
}

/// Per-world water configuration extracted from the world XML: the day clock
/// (glint direction follows the real directional light) and the `<Weather>`
/// wind (drives wave speed, slope and chop).
#[derive(Debug, Clone)]
pub struct WaterSurfaceConfig {
    /// `true` when a `<DayCycle>` drives the sun (shader derives the sun/moon
    /// glint from `Globals.time`); otherwise the static `<Sky>` sun.
    pub drive: bool,
    pub clock_start: f32,
    pub clock_speed: f32,
    pub dawn: f32,
    pub dusk: f32,
    pub max_elev: f32,
    /// Daytime floor of the directional light (`min-sun-elevation`).
    pub min_elev: f32,
    pub az_base: f32,
    /// Static sun used when there is no `<DayCycle>`.
    pub sun_elevation: f32,
    pub sun_azimuth: f32,
    pub wind: [f32; 2],
    pub wind_strength: f32,
    /// Amplitude das ondas — o maior `ripple` de qualquer `<Lake>` do mundo
    /// (0.2–2.0; default 1.0). Especializada como `CFG_WAVE_AMP`.
    pub wave_amp: f32,
}

impl Default for WaterSurfaceConfig {
    fn default() -> Self {
        Self {
            drive: false,
            clock_start: 480.0,
            clock_speed: 1.2,
            dawn: 330.0,
            dusk: 1170.0,
            max_elev: 62.0,
            min_elev: 8.0,
            az_base: 205.0,
            sun_elevation: 17.0,
            sun_azimuth: 205.0,
            wind: [0.7, 0.25],
            wind_strength: 1.5,
            wave_amp: 1.0,
        }
    }
}

impl WaterSurfaceConfig {
    /// Scan the parsed world for `<DayCycle>` and `<Weather>` and merge their
    /// values over the defaults (same walk as [`crate::sky::SkyConfig`]).
    pub fn from_world(entities: &[crate::recipes::EntitySpec]) -> WaterSurfaceConfig {
        let mut config = WaterSurfaceConfig::default();
        walk_entities(entities, &mut config);
        config
    }

    /// Rewrite the CONFIG const block of the shader template with this
    /// world's values (the rest of the template is untouched).
    pub fn render_world_shader(&self) -> String {
        let w = self.wind;
        let block = format!(
            "{CONFIG_BEGIN} (generated by `viber run` — edit the XML, not this block) ===\n\
const CFG_DRIVE: f32 = {};\n\
const CFG_CLOCK_START: f32 = {};\n\
const CFG_CLOCK_SPEED: f32 = {};\n\
const CFG_DAWN: f32 = {};\n\
const CFG_DUSK: f32 = {};\n\
const CFG_MAX_ELEV: f32 = {};\n\
const CFG_MIN_ELEV: f32 = {};\n\
const CFG_AZ_BASE: f32 = {};\n\
const CFG_SUN_ELEV: f32 = {};\n\
const CFG_SUN_AZ: f32 = {};\n\
const CFG_WIND_X: f32 = {};\n\
const CFG_WIND_Z: f32 = {};\n\
const CFG_WIND_STRENGTH: f32 = {};\n\
const CFG_WAVE_AMP: f32 = {};\n\
{CONFIG_END}",
            self.drive as i32,
            self.clock_start,
            self.clock_speed,
            self.dawn,
            self.dusk,
            self.max_elev,
            self.min_elev,
            self.az_base,
            self.sun_elevation,
            self.sun_azimuth,
            w[0],
            w[1],
            self.wind_strength,
            self.wave_amp,
        );
        let template = WATER_WGSL;
        let Some(begin) = template.find(CONFIG_BEGIN) else {
            return template.to_string();
        };
        let Some(end_rel) = template[begin..].find(CONFIG_END) else {
            return template.to_string();
        };
        let end = begin + end_rel + CONFIG_END.len();
        let mut out = String::with_capacity(template.len() + block.len());
        out.push_str(&template[..begin]);
        out.push_str(&block);
        out.push_str(&template[end..]);
        out
    }
}

fn walk_entities(specs: &[crate::recipes::EntitySpec], config: &mut WaterSurfaceConfig) {
    for spec in specs {
        match &spec.kind {
            crate::recipes::EntityKind::DayCycle {
                minute_of_day,
                minutes_per_real_second,
                dawn_minute,
                dusk_minute,
                max_sun_elevation,
                sun_azimuth_base,
                min_sun_elevation,
                ..
            } => {
                config.drive = true;
                config.clock_start = *minute_of_day;
                config.clock_speed = *minutes_per_real_second;
                config.dawn = *dawn_minute;
                config.dusk = *dusk_minute;
                config.max_elev = *max_sun_elevation;
                config.min_elev = *min_sun_elevation;
                config.az_base = *sun_azimuth_base;
            }
            crate::recipes::EntityKind::Weather {
                wind,
                wind_strength,
                ..
            } => {
                config.wind = *wind;
                config.wind_strength = *wind_strength;
            }
            // `ripple` do lago com o maior valor do mundo — é o multiplier
            // de amplitude das ondas (`CFG_WAVE_AMP`).
            crate::recipes::EntityKind::Lake { spec } => {
                config.wave_amp = config.wave_amp.max(spec.ripple.clamp(0.2, 2.0));
            }
            _ => {}
        }
        walk_entities(&spec.children, config);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physics::PhysicsSpec;
    use crate::recipes::{EntityKind, EntitySpec, TransformSpec};

    fn spec(kind: EntityKind) -> EntitySpec {
        EntitySpec {
            name: None,
            tag: None,
            script: None,
            destructible: None,
            transform: TransformSpec::default(),
            physics: PhysicsSpec::default(),
            kind,
            children: Vec::new(),
        }
    }

    /// O shader gerado substitui o bloco CONFIG e mantém o resto intacto.
    #[test]
    fn test_render_world_shader_specializes_config() {
        let mut config = WaterSurfaceConfig::default();
        config.drive = true;
        config.clock_start = 1140.0;
        config.wind_strength = 2.5;
        let shader = config.render_world_shader();
        assert!(shader.contains("const CFG_DRIVE: f32 = 1;"));
        assert!(shader.contains("const CFG_CLOCK_START: f32 = 1140;"));
        assert!(shader.contains("const CFG_WIND_STRENGTH: f32 = 2.5;"));
        // O corpo do shader sobrevive à substituição.
        assert!(shader.contains("fn fragment"));
        assert!(shader.contains("wave_normal"));
        assert_eq!(shader.matches(CONFIG_END).count(), 1);
    }

    /// O template compilado não pode levar overlays de debug. Um split de
    /// diagnóstico esquecido no WGSL passa despercebido em `cargo test` e em
    /// `cargo clippy` — só aparece na janela do jogo, e como o shader gerado
    /// só é reescrito no ARRANQUE, uma instância já aberta continua a
    /// mostrá-lo mesmo depois do fix. Esta guarda é o que trava isso.
    #[test]
    fn test_shader_template_has_no_debug_overlay() {
        for marker in ["DEBUG SPLIT", "DEBUG OVERLAY", "viewport.z / 3.0"] {
            assert!(
                !WATER_WGSL.contains(marker),
                "overlay de debug (`{marker}`) esquecido em water.wgsl"
            );
        }
        // O caminho normal termina no PBR, não num write directo de cor.
        assert!(WATER_WGSL.contains("out.color = main_pass_post_lighting_processing"));
    }

    /// `from_world` lê `<DayCycle>` e `<Weather>` (incl. filhos).
    #[test]
    fn test_water_config_from_world() {
        let world = vec![
            spec(EntityKind::Group),
            spec(EntityKind::DayCycle {
                minute_of_day: 1140.0,
                minutes_per_real_second: 3.0,
                dawn_minute: 330.0,
                dusk_minute: 1170.0,
                ambient_day: 0.26,
                ambient_night: 0.07,
                drive_ambient: true,
                max_sun_elevation: 55.0,
                sun_azimuth_base: 180.0,
                min_sun_elevation: 8.0,
            }),
            spec(EntityKind::Group).with_child(EntityKind::Weather {
                wind: [1.0, 0.0],
                wind_strength: 3.0,
                clouds: 0.25,
                rain: 0.0,
                cycle: true,
            }),
        ];
        let config = WaterSurfaceConfig::from_world(&world);
        assert!(config.drive);
        assert_eq!(config.clock_start, 1140.0);
        assert_eq!(config.max_elev, 55.0);
        assert_eq!(config.min_elev, 8.0);
        assert_eq!(config.wind, [1.0, 0.0]);
        assert_eq!(config.wind_strength, 3.0);
        // Defaults preservados na ausência de <Weather>/<DayCycle>.
        let bare = WaterSurfaceConfig::from_world(&[spec(EntityKind::Group)]);
        assert!(!bare.drive);
        assert_eq!(bare.wind_strength, 1.5);
    }

    impl EntitySpec {
        fn with_child(mut self, kind: EntityKind) -> EntitySpec {
            self.children.push(spec(kind));
            self
        }
    }
}
