// Camera-centred procedural sky. Colours are linear and already in the custom
// material's output space: do not apply StandardMaterial exposure a second time.
// The six vec4 storage fields must match sky.rs::SkyUniform (96 bytes).
#import bevy_render::view::View
#import bevy_pbr::forward_io::VertexOutput

@group(0) @binding(0) var<uniform> view: View;

struct SkyUniform {
    sun: vec4<f32>,       // direction to sun, daylight
    moon: vec4<f32>,      // direction to moon, night visibility
    zenith: vec4<f32>,    // linear colour, golden-hour weight
    horizon: vec4<f32>,   // linear colour, Weather coverage delta
    sun_tint: vec4<f32>,  // linear colour, virtual elapsed seconds
    params: vec4<f32>,    // wind x/z, reserved, minute of day (not a lunar calendar)
};
@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<storage, read> sky: SkyUniform;

const SKY_RADIANCE: f32 = 1.0;
// === WORLD CONFIG (generated by `viber run` — edit the XML, not this block) ===
const CFG_DRIVE: f32 = 1;
const CFG_CLOCK_START: f32 = 480;
const CFG_CLOCK_SPEED: f32 = 1.2;
const CFG_DAWN: f32 = 330;
const CFG_DUSK: f32 = 1170;
const CFG_MAX_ELEV: f32 = 62;
const CFG_AZ_BASE: f32 = 205;
const CFG_SUN_ELEV: f32 = 17;
const CFG_SUN_AZ: f32 = 205;
const CFG_MIE: f32 = 0.0035;
const CFG_MIE_G: f32 = 0.8;
const CFG_SUN_INTENSITY: f32 = 2.6;
const CFG_CLOUD_COVERAGE: f32 = 0.6;
const CFG_CLOUD_DENSITY: f32 = 0.55;
const CFG_CLOUD_ELEVATION: f32 = 0.55;
const CFG_STAR_DENSITY: f32 = 1;
const CFG_AURORA: f32 = 0.6;
const CFG_NEBULA: f32 = 0.5;
const CFG_WIND_X: f32 = 0.7;
const CFG_WIND_Z: f32 = 0.25;
// === END WORLD CONFIG ===

const PI: f32 = 3.141592653589793;
const TAU: f32 = 6.283185307179586;
const ROT: mat2x2<f32> = mat2x2<f32>(0.8, 0.6, -0.6, 0.8);

struct Atmosphere {
    sun: vec3<f32>,
    moon: vec3<f32>,
    zenith: vec3<f32>,
    horizon: vec3<f32>,
    tint: vec3<f32>,
    day: f32,
    night: f32,
    golden: f32,
};

fn safe_direction(v: vec3<f32>, fallback: vec3<f32>) -> vec3<f32> {
    if (dot(v, v) < 1e-10) { return fallback; }
    return v * inverseSqrt(dot(v, v));
}

fn atmosphere() -> Atmosphere {
    var a: Atmosphere;
    a.sun = safe_direction(sky.sun.xyz, vec3(0.0, 1.0, 0.0));
    a.moon = safe_direction(sky.moon.xyz, -a.sun);
    a.day = clamp(sky.sun.w, 0.0, 1.0);
    a.night = clamp(sky.moon.w, 0.0, 1.0);
    a.golden = clamp(sky.zenith.w, 0.0, 1.0);
    a.zenith = max(sky.zenith.rgb, vec3(0.0));
    a.horizon = max(sky.horizon.rgb, vec3(0.0));
    a.tint = max(sky.sun_tint.rgb, vec3(0.0));
    // Without DayCycle the CPU publishes a default daytime atmosphere, not
    // the authored static sun. Resolve that mode here, never from engine time.
    if (CFG_DRIVE < 0.5) {
        let el = radians(clamp(CFG_SUN_ELEV, -90.0, 90.0));
        let az = radians(CFG_SUN_AZ % 360.0);
        a.sun = vec3(cos(el) * sin(az), sin(el), cos(el) * cos(az));
        a.moon = -a.sun;
        a.day = smoothstep(-0.12, 0.18, a.sun.y);
        a.night = 1.0 - smoothstep(-0.18, 0.04, a.sun.y);
        a.golden = smoothstep(-0.14, -0.01, a.sun.y)
            * (1.0 - smoothstep(0.10, 0.48, a.sun.y));
        a.zenith = mix(vec3(0.004, 0.009, 0.025), vec3(0.085, 0.255, 0.62), a.day);
        a.horizon = mix(vec3(0.025, 0.038, 0.065), vec3(0.60, 0.755, 0.90), a.day);
        a.horizon = mix(a.horizon, vec3(0.78, 0.34, 0.15), a.golden * 0.65);
        a.tint = mix(vec3(1.0, 0.48, 0.20), vec3(1.0, 0.96, 0.88), smoothstep(0.0, 0.5, a.sun.y));
    }
    return a;
}

fn hash21(p: vec2<f32>) -> f32 {
    var q = fract(p * vec2(123.34, 456.21));
    q += dot(q, q + 45.32);
    return fract(q.x * q.y);
}

fn value_noise(p: vec2<f32>) -> f32 {
    let cell = floor(p);
    let f = fract(p);
    let u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    return mix(mix(hash21(cell), hash21(cell + vec2(1.0, 0.0)), u.x),
        mix(hash21(cell + vec2(0.0, 1.0)), hash21(cell + vec2(1.0)), u.x), u.y);
}

// Unresolved octaves converge to their mean instead of shimmering or changing
// cloud coverage as the camera rotates. Footprints are computed before branches.
fn fbm(p: vec2<f32>, footprint: f32) -> f32 {
    var uv = p;
    var width = footprint;
    var amplitude = 0.5;
    var sum = 0.0;
    for (var i = 0; i < 5; i++) {
        let resolved = 1.0 - smoothstep(0.25, 0.85, width);
        sum += amplitude * mix(0.5, value_noise(uv), resolved);
        uv = ROT * uv * 2.03 + vec2(11.7, 5.3);
        width *= 2.03;
        amplitude *= 0.5;
    }
    return sum / 0.96875;
}

fn tangent(axis: vec3<f32>) -> vec3<f32> {
    let reference = select(vec3(0.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0), abs(axis.y) > 0.95);
    return normalize(cross(reference, axis));
}

fn sky_gradient(dir: vec3<f32>, a: Atmosphere) -> vec3<f32> {
    let height = max(dir.y, 0.0);
    let horizon_weight = exp(-height * 4.2);
    var color = mix(a.zenith, a.horizon, horizon_weight);
    // Horizontal dot stays continuous at the zenith; normalizing dir.xz does not.
    let facing = clamp(dot(dir.xz, a.sun.xz), 0.0, 1.0);
    let sunset = exp(-height * 2.8) * a.golden;
    color = mix(color, a.tint * vec3(0.80, 0.66, 0.56), sunset * (0.14 + 0.36 * facing * facing));
    // Continue the horizon into the lower hemisphere, without a mirrored zenith
    // or a cusp at y=0. Distant terrain/fog can cover this smoothly at any pitch.
    let below = 1.0 - exp(min(dir.y, 0.0) * 3.0);
    return mix(color, a.horizon * 0.42, below);
}

fn sun_light(dir: vec3<f32>, a: Atmosphere, pixel: f32) -> vec3<f32> {
    let radius = 0.014;
    let distance = length(dir - a.sun);
    let aa = max(pixel * 0.65, 0.00015);
    let disc = 1.0 - smoothstep(radius - aa, radius + aa, distance);
    let mu = clamp(dot(dir, a.sun), -1.0, 1.0);
    let g = clamp(CFG_MIE_G, 0.0, 0.96);
    // Normalised Henyey-Greenstein lobe: bounded even for g close to one.
    let denominator = max(1.0 + g * g - 2.0 * g * mu, 0.0016);
    let mie = pow((1.0 - g) * (1.0 - g) / denominator, 1.5);
    let halo = exp(-distance * distance * 90.0) * 0.32;
    let visible = smoothstep(-0.055, 0.005, a.sun.y)
        * smoothstep(-radius, 0.002, dir.y);
    let glow = mie * clamp(CFG_MIE * 120.0, 0.0, 1.6) + halo;
    return a.tint * (disc * 24.0 + glow) * clamp(CFG_SUN_INTENSITY, 0.0, 32.0) * visible;
}

fn moon_light(dir: vec3<f32>, a: Atmosphere, pixel: f32) -> vec3<f32> {
    if (a.night <= 0.0 || a.moon.y < -0.05) { return vec3(0.0); }
    let radius = 0.018;
    let distance = length(dir - a.moon);
    let aa = max(pixel * 0.65, 0.00015);
    let disc = 1.0 - smoothstep(radius - aa, radius + aa, distance);
    let right = tangent(a.moon);
    let up = cross(a.moon, right);
    let local = vec2(dot(dir, right), dot(dir, up)) / radius;
    let z = sqrt(max(1.0 - dot(local, local), 0.0));
    // Geometric, stylised phase: the existing moon orbit is not a lunar calendar.
    let normal = safe_direction(right * local.x + up * local.y - a.moon * z, -a.moon);
    let incidence = dot(normal, a.sun);
    let terminator = smoothstep(-0.035, 0.035, incidence);
    let maria = fbm(local * 3.5 + vec2(17.3, 4.8), pixel / radius * 3.5);
    let surface = (0.68 + 0.32 * maria) * (0.025 + terminator * (0.30 + 0.70 * max(incidence, 0.0)));
    let phase = clamp((1.0 - dot(a.sun, a.moon)) * 0.5, 0.0, 1.0);
    let halo = (exp(-distance * distance * 700.0) * 0.12
        + exp(-distance * distance * 75.0) * 0.025) * phase;
    let visible = a.night * smoothstep(-0.04, 0.03, a.moon.y) * smoothstep(-0.01, 0.04, dir.y);
    return vec3(0.80, 0.87, 1.0) * (surface * disc * 2.0 + halo) * visible;
}

// Stars are points ON the sphere, not intersections with 3D noise cells.
// Longitude wraps per latitude band, so neither the meridian nor the poles
// introduce clipped squares. Neighbouring cells retain the whole point spread.
fn star_field(dir: vec3<f32>, time: f32, night: f32, pixel: f32) -> vec3<f32> {
    if (night <= 0.0 || CFG_STAR_DENSITY <= 0.0 || dir.y <= 0.0) { return vec3(0.0); }
    let rows = 72.0;
    let latitude = asin(clamp(dir.y, -1.0, 1.0));
    let longitude = atan2(dir.z, dir.x);
    let row = floor((latitude / PI + 0.5) * rows);
    var color = vec3(0.0);
    for (var j = -1; j <= 1; j++) {
        let r = row + f32(j);
        if (r < 0.0 || r >= rows) { continue; }
        let lat_center = ((r + 0.5) / rows - 0.5) * PI;
        let columns = max(1.0, floor(2.0 * rows * cos(lat_center)));
        let column = floor((longitude / TAU + 0.5) * columns);
        for (var i = -1; i <= 1; i++) {
            // Avoid counting the same star multiple times in a polar band.
            if (abs(f32(i)) > 0.0 && columns < 3.0) { continue; }
            let c = (column + f32(i) + columns) % columns;
            let cell = vec2(c, r);
            let seed = hash21(cell + vec2(91.4, 13.7));
            if (seed >= clamp(CFG_STAR_DENSITY * 0.10, 0.0, 1.0)) { continue; }
            let lat = ((r + 0.2 + 0.6 * hash21(cell + vec2(8.1))) / rows - 0.5) * PI;
            let lon = ((c + 0.2 + 0.6 * hash21(cell + vec2(3.7))) / columns - 0.5) * TAU;
            let center = vec3(cos(lat) * cos(lon), sin(lat), cos(lat) * sin(lon));
            let delta = dir - center;
            let intrinsic = mix(0.00045, 0.00115, pow(hash21(cell + vec2(27.0)), 5.0));
            let variance = intrinsic * intrinsic + pixel * pixel * 0.22;
            let point = exp(-dot(delta, delta) / (2.0 * variance)) * intrinsic * intrinsic / variance;
            let twinkle = 0.92 + 0.08 * sin(time * (1.1 + seed) + seed * 321.0);
            let tint = mix(vec3(0.66, 0.80, 1.0), vec3(1.0, 0.79, 0.56), hash21(cell + vec2(43.0)));
            color += tint * point * twinkle * 4.0;
        }
    }
    return color * night * night * smoothstep(0.0, 0.22, dir.y);
}

fn milky_way(dir: vec3<f32>, night: f32, pixel: f32) -> vec3<f32> {
    if (night <= 0.0 || CFG_NEBULA <= 0.0) { return vec3(0.0); }
    let axis = normalize(vec3(0.42, 0.62, -0.66));
    let latitude = dot(dir, axis);
    let band = exp(-latitude * latitude * 95.0);
    let dust = fbm(vec2(dot(dir, tangent(axis)), dir.y) * 8.0, pixel * 8.0);
    return vec3(0.16, 0.20, 0.30) * band * (0.25 + dust * 0.75)
        * clamp(CFG_NEBULA, 0.0, 4.0) * night * night * 0.45 * smoothstep(0.0, 0.3, dir.y);
}

fn aurora_ribbons(dir: vec3<f32>, time: f32, night: f32, pixel: f32) -> vec3<f32> {
    if (night <= 0.0 || CFG_AURORA <= 0.0 || dir.y <= 0.0) { return vec3(0.0); }
    let drift = vec2(time * 0.008, 0.0);
    let wave = fbm(dir.xz * 2.0 + drift, pixel * 2.0);
    let altitude = 0.30 + wave * 0.25;
    // pow() with a negative base is UB in WGSL (log2(neg) = NaN): dir.y below
    // the wave-driven altitude is the common case, so square the value
    // directly instead — same curtain, no poisoned sky when night > 0.
    let d = (dir.y - altitude) * 12.0;
    let curtain = exp(-d * d);
    let strands = fbm(vec2(dir.x * 17.0 + wave * 3.0, dir.z * 2.0) + drift, pixel * 17.0);
    let mask = curtain * smoothstep(0.44, 0.74, strands);
    let tint = mix(vec3(0.08, 0.65, 0.30), vec3(0.25, 0.22, 0.60), smoothstep(altitude, altitude + 0.13, dir.y));
    return tint * mask * clamp(CFG_AURORA, 0.0, 4.0) * night * night * 0.30;
}

fn meteor(dir: vec3<f32>, time: f32, night: f32, pixel: f32) -> vec3<f32> {
    if (night < 0.25) { return vec3(0.0); }
    let window = floor(time / 17.0);
    let seed = hash21(vec2(window, 37.1));
    let age = time - window * 17.0 - 2.0;
    if (seed < 0.65 || age < 0.0 || age > 0.9) { return vec3(0.0); }
    let az = seed * TAU;
    let start = normalize(vec3(sin(az), 0.8, cos(az)));
    let along = tangent(start);
    let across = cross(start, along);
    let angle = atan2(dot(dir, along), dot(dir, start));
    let head = age * 0.30;
    let behind = head - angle;
    let width = max(0.0008, pixel * 0.6);
    let across_distance = dot(dir, across) / width;
    let line = exp(-across_distance * across_distance);
    let trail = smoothstep(0.0, 0.008, behind) * (1.0 - smoothstep(0.015, 0.10, behind));
    let life = smoothstep(0.0, 0.08, age) * (1.0 - smoothstep(0.55, 0.9, age));
    return vec3(0.65, 0.80, 1.0) * line * trail * life * night * smoothstep(0.0, 0.2, dir.y)
        * step(0.0, dot(dir, start)) * 1.4;
}

// Intersection with a gently curved cloud shell; the rationalised positive
// root avoids cancellation at the zenith and a 1/y singularity at the horizon.
fn cloud_projection(dir: vec3<f32>, height: f32) -> f32 {
    let curvature = 0.035;
    let shell = height * (2.0 + curvature * height);
    return shell / (sqrt(dir.y * dir.y + curvature * shell) + max(dir.y, 0.0));
}

fn cloud_density(uv: vec2<f32>, coverage: f32, footprint: f32) -> f32 {
    let shape = fbm(uv, footprint);
    let threshold = mix(0.82, 0.18, coverage);
    return smoothstep(threshold, threshold + 0.20, shape) * smoothstep(0.0, 0.06, coverage);
}

fn cirrus_layer(dir: vec3<f32>, color: vec3<f32>, a: Atmosphere, wind: vec2<f32>, time: f32, coverage: f32, pixel: f32) -> vec3<f32> {
    let travel = cloud_projection(dir, 2.6);
    let uv = dir.xz * travel * 0.55 + wind * time * 0.0018;
    let stretched = vec2(uv.x * 0.55 - uv.y * 0.25, uv.y * 3.0);
    let noise = fbm(stretched, pixel * travel * 1.8);
    let alpha = smoothstep(0.48, 0.76, noise) * smoothstep(0.0, 0.3, dir.y)
        * coverage * clamp(CFG_CLOUD_DENSITY, 0.0, 1.0) * 0.35;
    let tint = mix(vec3(0.015, 0.022, 0.040), mix(vec3(0.82, 0.87, 0.95), a.tint, a.golden * 0.7), a.day);
    return mix(color, tint, alpha);
}

fn cumulus_layer(dir: vec3<f32>, color: vec3<f32>, a: Atmosphere, wind: vec2<f32>, time: f32, coverage: f32, pixel: f32) -> vec3<f32> {
    let height = mix(0.7, 2.4, clamp(CFG_CLOUD_ELEVATION, 0.0, 1.0));
    let travel = cloud_projection(dir, height);
    let drift = wind * time * 0.004;
    let uv = dir.xz * travel * 0.55 + drift;
    let footprint = pixel * travel * 0.8 / max(dir.y, 0.18);
    let base = cloud_density(uv, coverage, footprint);
    let middle = cloud_density(uv + dir.xz * 0.13, coverage, footprint);
    let top = cloud_density(uv + dir.xz * 0.29, coverage, footprint);
    let mass = base * 0.45 + middle * 0.35 + top * 0.20;
    let depth = mass * clamp(CFG_CLOUD_DENSITY, 0.0, 4.0) * 5.0 / max(dir.y, 0.30);
    let alpha = (1.0 - exp(-depth)) * smoothstep(0.0, 0.075, dir.y);
    if (alpha < 0.001) { return color; }
    let light_dir = select(a.moon, a.sun, a.day > 0.15);
    let blocker = cloud_density(uv + light_dir.xz * 0.48, coverage, footprint);
    // More matter towards the light means LESS transmitted light, not more.
    let transmission = exp(-blocker * clamp(CFG_CLOUD_DENSITY, 0.0, 4.0) * 4.0);
    let shade = clamp(0.28 + transmission * 0.62 + (top - base) * 0.18, 0.0, 1.0);
    let shadow = mix(vec3(0.012, 0.018, 0.032), a.zenith * 0.45 + vec3(0.16), a.day);
    let daylight = mix(vec3(0.95, 0.97, 1.0), a.tint * vec3(0.98, 0.86, 0.74), a.golden * 0.8);
    let lit = mix(vec3(0.055, 0.070, 0.10), daylight, a.day);
    var cloud = mix(shadow, lit, shade);
    let forward = pow(max(dot(dir, light_dir), 0.0), 12.0);
    let rim = 4.0 * mass * (1.0 - mass) * transmission * forward;
    cloud += mix(vec3(0.06, 0.08, 0.12), a.tint, a.day) * rim * 0.40;
    cloud = mix(cloud, a.horizon, (1.0 - smoothstep(0.0, 0.25, dir.y)) * 0.6);
    return mix(color, cloud, alpha);
}

fn evaluate_sky(dir: vec3<f32>, pixel_angle: f32) -> vec3<f32> {
    let a = atmosphere();
    let pixel = clamp(pixel_angle, 0.00001, 0.1);
    let time = sky.sun_tint.w;
    var color = sky_gradient(dir, a);
    color += milky_way(dir, a.night, pixel);
    color += star_field(dir, time, a.night, pixel);
    color += aurora_ribbons(dir, time, a.night, pixel);
    color += meteor(dir, time, a.night, pixel);
    color += moon_light(dir, a, pixel);
    color += sun_light(dir, a, pixel);
    let coverage = clamp(CFG_CLOUD_COVERAGE + sky.horizon.w, 0.0, 1.0);
    if (dir.y > 0.0 && coverage > 0.0 && CFG_CLOUD_DENSITY > 0.0) {
        let wind = sky.params.xy;
        // High cirrus sits behind low cumulus; both attenuate celestial light.
        color = cirrus_layer(dir, color, a, wind, time, coverage, pixel);
        color = cumulus_layer(dir, color, a, wind, time, coverage, pixel);
    }
    return max(color, vec3(0.0)) * SKY_RADIANCE;
}

@fragment
fn fragment(mesh: VertexOutput) -> @location(0) vec4<f32> {
    let dir = safe_direction(mesh.world_position.xyz - view.world_from_view[3].xyz, vec3(0.0, 1.0, 0.0));
    // Derivatives must be evaluated in uniform control flow, before night/cloud
    // branches. Pass the angular footprint through every procedural layer.
    let pixel = max(length(dpdx(dir)), length(dpdy(dir)));
    return vec4(evaluate_sky(dir, pixel), 1.0);
}
