import type { Plugin } from '../../core';
import type { SceneManifest } from './loader';

export interface SceneManifestPluginConfig {
  /** URL to gameassets_manifest.json (generated by GameAssets Python pipeline) */
  manifestUrl?: string;
  /** Base path for resolving relative asset URLs */
  basePath?: string;
}

/**
 * Plugin that integrates the GameAssets pipeline manifest with the VibeGame scene loader.
 *
 * The GameAssets Python pipeline (Shared/src/gamedev_shared/pipeline/manifest.py) produces
 * a `gameassets_manifest.json` file with typed asset entries. This plugin bridges that
 * pipeline output into the engine's scene loading system.
 *
 * Usage:
 * ```ts
 * // Auto-load manifest on scene init
 * const plugin = SceneManifestPlugin.create({ manifestUrl: '/assets/gameassets_manifest.json' });
 * // Or manually:
 * const manifest = await loadSceneManifest(state, '/assets/gameassets_manifest.json');
 * ```
 */
export const SceneManifestPlugin: Plugin & {
  create?: (config?: SceneManifestPluginConfig) => Plugin;
} = {
  systems: [],
  components: {},

  create(config?: SceneManifestPluginConfig): Plugin {
    return {
      name: 'scene-manifest',
      systems: [],
      components: {},
      meta: {
        manifestUrl: config?.manifestUrl,
        basePath: config?.basePath ?? '/',
      },
    };
  },
};
