import type { Plugin } from '../../core';

export interface SceneManifestPluginConfig {
  /** URL to gameassets_manifest.json (generated by GameAssets Python pipeline) */
  manifestUrl?: string;
  /** Base path for resolving relative asset URLs */
  basePath?: string;
}

/** Helper to create typed config for scene manifest loading. */
export function createSceneManifestConfig(
  config?: SceneManifestPluginConfig
): Required<SceneManifestPluginConfig> {
  return {
    manifestUrl: config?.manifestUrl ?? '/gameassets_manifest.json',
    basePath: config?.basePath ?? '/',
  };
}

/**
 * Plugin that integrates the GameAssets pipeline manifest with the VibeGame scene loader.
 *
 * The GameAssets Python pipeline (Shared/src/gamedev_shared/pipeline/manifest.py) produces
 * a `gameassets_manifest.json` file with typed asset entries. This plugin bridges that
 * pipeline output into the engine's scene loading system.
 *
 * Usage:
 * ```ts
 * import { SceneManifestPlugin, loadSceneManifest, createSceneManifestConfig } from './plugins/scene-manifest';
 * // registerPlugin(SceneManifestPlugin)
 * // Then:
 * const cfg = createSceneManifestConfig({ manifestUrl: '/assets/gameassets_manifest.json' });
 * const manifest = await loadSceneManifest(state, cfg.manifestUrl, cfg.basePath);
 * ```
 */
export const SceneManifestPlugin: Plugin = {
  systems: [],
  components: {},
};
