// Viber grass — wind-animated vertex stage for the instanced grass field
// (`src/grass.rs`).
//
// Only the VERTEX stage is custom: the material is
// `ExtendedMaterial<StandardMaterial, GrassExtension>`, so the fragment stays
// the stock PBR path (lighting, shadows, fog, tonemapping all unchanged) and
// the per-blade colour arrives as vertex colours.
//
// Mesh contract (baked by `grass.rs`):
//   POSITION  blade vertex in world-ish tile space (the tile entity sits at
//             the tile origin, blades are already terrain-seated)
//   NORMAL    the *terrain* normal at the blade root — grass shades like the
//             ground it grows on instead of going black edge-on
//   UV_0      x = height fraction along the blade (0 root → 1 tip)
//             y = blade height in meters (the bend amplitude scale)
//   COLOR     per-blade tint (root darker, tip lighter, hue jittered)
//
// WORLD CONFIG below is rewritten by `grass.rs` from `<Weather wind=…>` before
// the shader asset is inserted — a custom material *uniform* would never be
// re-uploaded (Bevy 0.19 slot-1 storage promotion), which is the same reason
// `sky.wgsl` / `layers.wgsl` specialize by consts.

#import bevy_pbr::{
    mesh_functions,
    forward_io::{Vertex, VertexOutput},
    view_transformations::position_world_to_clip,
    mesh_view_bindings::globals,
}

// === WORLD CONFIG (generated by src/grass.rs — edit the XML, not this block) ===
const CFG_WIND_X: f32 = 0.94;
const CFG_WIND_Z: f32 = 0.34;
const CFG_WIND_STRENGTH: f32 = 1.0;
// === END WORLD CONFIG ===

/// Meters per full gust wave travelling across the field. Long waves are what
/// makes a meadow read as one surface breathing instead of N twitching props.
const GUST_WAVELENGTH: f32 = 34.0;
/// Gust travel speed (m/s).
const GUST_SPEED: f32 = 9.0;
/// Baseline lean even between gusts (fraction of blade height).
const BEND_BASE: f32 = 0.20;
/// Extra lean at the crest of a gust (fraction of blade height). r1's wind
/// was there but invisible: the whole field leaned by the same small amount,
/// so nothing ever *moved past* anything. The gust now dominates the base
/// lean, and the crest is sharpened below so a distinct band of flattened
/// grass travels across the meadow — the BOTW wave.
const BEND_GUST: f32 = 0.52;
/// Exponent on the gust crest: >1 turns a sine into a narrow travelling band
/// with calm between the waves.
const GUST_SHARPNESS: f32 = 1.9;
/// Per-blade flutter amplitude and rate — breaks the wave into blades.
const FLUTTER_AMP: f32 = 0.13;
const FLUTTER_RATE: f32 = 4.9;

@vertex
fn vertex(vertex: Vertex) -> VertexOutput {
    var out: VertexOutput;

    let world_from_local = mesh_functions::get_world_from_local(vertex.instance_index);
    var world = mesh_functions::mesh_position_local_to_world(
        world_from_local,
        vec4<f32>(vertex.position, 1.0),
    );

    // ---- wind -----------------------------------------------------------
    // `h` is the height fraction; the bend grows as h² so the root stays
    // planted and only the top half of the blade travels.
    let h = clamp(vertex.uv.x, 0.0, 1.0);
    let blade_height = vertex.uv.y;
    let t = globals.time;
    let wind_dir = normalize(vec2<f32>(CFG_WIND_X, CFG_WIND_Z) + vec2<f32>(1e-5, 0.0));

    // Travelling gust: a wave sweeping the field along the wind direction.
    let along = dot(world.xz, wind_dir);
    let wave = sin((along - t * GUST_SPEED) * (6.2831853 / GUST_WAVELENGTH)) * 0.5 + 0.5;
    let gust = pow(wave, GUST_SHARPNESS);
    // Second, slower and longer wave so gusts never repeat on a fixed beat.
    let swell = sin((along - t * GUST_SPEED * 0.37) * (6.2831853 / (GUST_WAVELENGTH * 3.1)))
        * 0.5 + 0.5;
    // Per-blade flutter, phased by world position so neighbours differ.
    let flutter = sin(t * FLUTTER_RATE + world.x * 3.7 + world.z * 2.9);

    let lean = (BEND_BASE + BEND_GUST * mix(gust, swell, 0.35) + FLUTTER_AMP * flutter)
        * CFG_WIND_STRENGTH;
    let travel = lean * h * h * blade_height;
    // Cross-wind sway: without it every blade in the world travels on one
    // axis and the field shears like a flag. A small perpendicular wobble at
    // a different rate is what makes it read as air, not as a transform.
    let cross_dir = vec2<f32>(-wind_dir.y, wind_dir.x);
    let cross = sin(t * FLUTTER_RATE * 0.63 + world.x * 2.3 - world.z * 3.3)
        * FLUTTER_AMP * 1.6 * h * h * blade_height * CFG_WIND_STRENGTH;
    world = vec4<f32>(
        world.x + wind_dir.x * travel + cross_dir.x * cross,
        // Sink the tip as it leans so the blade keeps roughly its length
        // instead of stretching out of the ground.
        world.y - travel * travel * 0.55 / max(blade_height, 0.05),
        world.z + wind_dir.y * travel + cross_dir.y * cross,
        world.w,
    );

    out.world_position = world;
    out.position = position_world_to_clip(world.xyz);
    out.world_normal = mesh_functions::mesh_normal_local_to_world(
        vertex.normal,
        vertex.instance_index,
    );

#ifdef VERTEX_UVS_A
    out.uv = vertex.uv;
#endif
#ifdef VERTEX_UVS_B
    out.uv_b = vertex.uv_b;
#endif
#ifdef VERTEX_TANGENTS
    out.world_tangent = mesh_functions::mesh_tangent_local_to_world(
        world_from_local,
        vertex.tangent,
        vertex.instance_index,
    );
#endif
#ifdef VERTEX_COLORS
    out.color = vertex.color;
#endif
#ifdef VERTEX_OUTPUT_INSTANCE_INDEX
    out.instance_index = vertex.instance_index;
#endif
#ifdef VISIBILITY_RANGE_DITHER
    out.visibility_range_dither = mesh_functions::get_visibility_range_dither_level(
        vertex.instance_index,
        world_from_local[3],
    );
#endif

    return out;
}
