import { BodyType, ColliderShape } from '../physics';

export const PLAYER_BODY_DEFAULTS = {
  type: BodyType.KinematicPositionBased,
  mass: 1,
  posX: 0,
  posY: 0,
  posZ: 0,
  rotX: 0,
  rotY: 1,
  rotZ: 0,
  rotW: 0,
  eulerX: 0,
  eulerY: 180,
  eulerZ: 0,
  velX: 0,
  velY: 0,
  velZ: 0,
  rotVelX: 0,
  rotVelY: 0,
  rotVelZ: 0,
  linearDamping: 0,
  angularDamping: 0,
  gravityScale: 1,
  ccd: 1,
  lockRotX: 1,
  lockRotY: 0,
  lockRotZ: 1,
} as const;

export const PLAYER_COLLIDER_DEFAULTS = {
  shape: ColliderShape.Capsule,
  radius: 0.3,
  height: 0.9,
  sizeX: 1,
  sizeY: 1,
  sizeZ: 1,
  friction: 0,
  restitution: 0,
  density: 1,
  isSensor: 0,
  membershipGroups: 0xffff,
  filterGroups: 0xffff,
  posOffsetX: 0,
  posOffsetY: 0.75,
  posOffsetZ: 0,
  rotOffsetX: 0,
  rotOffsetY: 0,
  rotOffsetZ: 0,
  rotOffsetW: 1,
} as const;
