"""Asset category system: type-specific hints and generation defaults."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AssetCategory:
    name: str
    default_kind: str
    target_faces: int
    hint_2d: str
    hint_3d: str
    hint_rig: str
    hint_parts: str
    hint_texture: str
    extra_negatives: tuple[str, ...] = ()


CATEGORIES: dict[str, AssetCategory] = {
    "humanoid": AssetCategory(
        name="humanoid",
        default_kind="character",
        target_faces=32000,
        hint_2d="full-body character concept, front-facing view, clean silhouette on white background",
        hint_3d="single character model, no weapons or props attached, clean mesh with clear limb separation",
        hint_rig=(
            "standing in A-pose or T-pose with arms extended away from body, "
            "front-facing neutral pose, symmetrical stance, fingers spread slightly"
        ),
        hint_parts=(
            "designed with clear separable segments at joints, "
            "head removable at neck, limbs separable at shoulders and hips"
        ),
        hint_texture="smlstxtr, human skin fabric texture, seamless texture",
        extra_negatives=(
            "held weapon",
            "held item",
            "holding sword",
            "holding shield",
            "holding staff",
            "holding object",
            "equipped gear",
            "wearing armor",
            "carrying backpack",
            "holding potion",
            "holding bag",
            "holding torch",
            "carrying items",
            "accessories in hands",
        ),
    ),
    "creature": AssetCategory(
        name="creature",
        default_kind="character",
        target_faces=24000,
        hint_2d="creature concept art, side view, clear silhouette on white background",
        hint_3d="single creature model, no rider or accessories, clean organic mesh",
        hint_rig="standing in neutral pose with legs apart, arms or forelimbs extended, symmetrical stance",
        hint_parts=(
            "designed with clear separable segments, "
            "head removable at neck, limbs separable at joints, tail as separate piece"
        ),
        hint_texture="smlstxtr, creature scales skin pattern, seamless texture",
        extra_negatives=(
            "rider",
            "saddle",
            "reins",
            "worn armor",
            "accessories",
            "collar with tag",
            "ridden by character",
        ),
    ),
    "chest": AssetCategory(
        name="chest",
        default_kind="prop",
        target_faces=8000,
        hint_2d="game chest or treasure box, front view, clear lid visible on white background",
        hint_3d="isolated chest or container, no hands or characters, clean geometry with visible lid seam",
        hint_rig="",
        hint_parts="chest with clearly separate lid, visible hinge line, distinct top and bottom halves",
        hint_texture="smlstxtr, wood metal chest surface, seamless texture",
        extra_negatives=(
            "scattered coins",
            "spilling treasure",
            "loot on ground",
            "open contents visible",
            "gold pile",
            "gems scattered",
            "overflowing items",
        ),
    ),
    "weapon": AssetCategory(
        name="weapon",
        default_kind="prop",
        target_faces=6000,
        hint_2d="game weapon, side view, clean silhouette on white background",
        hint_3d="single clean weapon, no hands or characters holding it, isolated tool",
        hint_rig="",
        hint_parts="weapon with separable blade and handle, clear join line between grip and striking surface",
        hint_texture="smlstxtr, metal blade wood handle material, seamless texture",
        extra_negatives=(
            "hand holding",
            "hands gripping",
            "person holding weapon",
            "character wielding",
            "arm attached",
            "fingers wrapped",
            "body part",
        ),
    ),
    "tree": AssetCategory(
        name="tree",
        default_kind="environment",
        target_faces=12000,
        hint_2d="game-ready tree, full view, trunk and canopy visible on white background",
        hint_3d="stylized game tree, clean trunk and canopy separation",
        hint_rig="",
        hint_parts="tree with separable trunk, branches, and foliage canopy layers",
        hint_texture="smlstxtr, tree bark leaf foliage, seamless texture",
    ),
    "rock": AssetCategory(
        name="rock",
        default_kind="prop",
        target_faces=3200,
        hint_2d="game-ready rock formation, single isolated boulder, white background",
        hint_3d="simple rock or boulder, low-poly friendly, no attached ground plane",
        hint_rig="",
        hint_parts="",
        hint_texture="smlstxtr, rock stone surface detail, seamless texture",
    ),
    "mineral": AssetCategory(
        name="mineral",
        default_kind="prop",
        target_faces=4800,
        hint_2d="crystal or mineral cluster, front view, faceted surfaces on white background",
        hint_3d="crystal formation with distinct facets, clean geometry, no ground attachment",
        hint_rig="",
        hint_parts="mineral with separable crystal shards, each crystal removable from cluster base",
        hint_texture="smlstxtr, crystal gem mineral surface, seamless texture",
    ),
    "building": AssetCategory(
        name="building",
        default_kind="environment",
        target_faces=24000,
        hint_2d="game building or structure, front view, architectural detail on white background",
        hint_3d="isolated building model, no terrain or ground plane, clean structural geometry",
        hint_rig="",
        hint_parts="building with separable roof, walls, door, and window sections",
        hint_texture="smlstxtr, stone brick wall surface, seamless texture",
    ),
    "furniture": AssetCategory(
        name="furniture",
        default_kind="prop",
        target_faces=8000,
        hint_2d="game furniture piece, front view, clean proportions on white background",
        hint_3d="isolated furniture item, no room or floor, clean geometry with visible part lines",
        hint_rig="",
        hint_parts="furniture with clearly separate seat, backrest, legs, and armrests",
        hint_texture="smlstxtr, wood furniture surface grain, seamless texture",
    ),
    "vegetation": AssetCategory(
        name="vegetation",
        default_kind="environment",
        target_faces=10000,
        hint_2d="game vegetation or plant, full view, leaf detail visible on white background",
        hint_3d="vegetation cluster, clean stem and leaf separation, no ground plane",
        hint_rig="",
        hint_parts="vegetation with separable leaves, stems, and flower or fruit sections",
        hint_texture="smlstxtr, green leaf grass vegetation, seamless texture",
    ),
    "vehicle": AssetCategory(
        name="vehicle",
        default_kind="prop",
        target_faces=16000,
        hint_2d="game vehicle, side view, mechanical detail on white background",
        hint_3d="isolated vehicle model, no driver or terrain, clean mechanical geometry",
        hint_rig="",
        hint_parts="vehicle with separable wheels or treads, body shell, and internal components",
        hint_texture="smlstxtr, metal vehicle paint surface, seamless texture",
    ),
    "armor": AssetCategory(
        name="armor",
        default_kind="prop",
        target_faces=10000,
        hint_2d="game armor piece, front view, clean surfaces on white background",
        hint_3d="isolated armor piece, no body or character inside, clean plate geometry",
        hint_rig="laid flat or in T-pose arrangement, armor open and unfolded",
        hint_parts="armor with separable plates, straps, and padding layers",
        hint_texture="smlstxtr, metal armor plate leather, seamless texture",
    ),
    "food": AssetCategory(
        name="food",
        default_kind="prop",
        target_faces=3200,
        hint_2d="game food item, top-down or front view, simple organic shape on white background",
        hint_3d="isolated food item, no plate or table, clean simple organic geometry",
        hint_rig="",
        hint_parts="food with separable layers or sections where applicable",
        hint_texture="smlstxtr, food surface detail organic, seamless texture",
    ),
    "tool": AssetCategory(
        name="tool",
        default_kind="prop",
        target_faces=4000,
        hint_2d="game tool or implement, side view, clean handle and head on white background",
        hint_3d="single clean tool, no hands or characters, clean silhouette with handle and head",
        hint_rig="",
        hint_parts="tool with separable handle and working head or tip",
        hint_texture="smlstxtr, wood metal tool surface, seamless texture",
    ),
    "terrain": AssetCategory(
        name="terrain",
        default_kind="environment",
        target_faces=16000,
        hint_2d="terrain tile or ground chunk, top-down view, surface detail on white background",
        hint_3d="ground chunk or terrain tile, flat bottom surface, no full landscape",
        hint_rig="",
        hint_parts="terrain with separable surface layers, ground, grass, and stone overlays",
        hint_texture="smlstxtr, ground dirt grass terrain, seamless texture",
    ),
    "effects": AssetCategory(
        name="effects",
        default_kind="prop",
        target_faces=2000,
        hint_2d="visual effect element, abstract shape, simple form on white background",
        hint_3d="abstract effect mesh, very low complexity, single element",
        hint_rig="",
        hint_parts="",
        hint_texture="smlstxtr, glowing energy particle surface, seamless texture",
    ),
}

# Keyword mapping for infer_category: maps lowercase tokens to category keys.
_KEYWORD_MAP: dict[str, str] = {
    # humanoid
    "humanoid": "humanoid",
    "human": "humanoid",
    "person": "humanoid",
    "personagem": "humanoid",
    "pessoa": "humanoid",
    "guerreiro": "humanoid",
    "guerreira": "humanoid",
    "warrior": "humanoid",
    "knight": "humanoid",
    "cavaleiro": "humanoid",
    "mage": "humanoid",
    "mago": "humanoid",
    "hero": "humanoid",
    "heroi": "humanoid",
    "heroina": "humanoid",
    "npc": "humanoid",
    "villager": "humanoid",
    "soldier": "humanoid",
    "soldado": "humanoid",
    "archer": "humanoid",
    "arqueiro": "humanoid",
    # creature
    "creature": "creature",
    "criatura": "creature",
    "monster": "creature",
    "monstro": "creature",
    "animal": "creature",
    "beast": "creature",
    "besta": "creature",
    "dragon": "creature",
    "dragao": "creature",
    "demon": "creature",
    "demônio": "creature",
    "goblin": "humanoid",
    "orc": "humanoid",
    "wolf": "creature",
    "lobo": "creature",
    "bear": "creature",
    "urso": "creature",
    # chest
    "chest": "chest",
    "bau": "chest",
    "baú": "chest",
    "treasure": "chest",
    "tesouro": "chest",
    "box": "chest",
    "caixa": "chest",
    "crate": "chest",
    "coffer": "chest",
    # weapon
    "weapon": "weapon",
    "arma": "weapon",
    "sword": "weapon",
    "espada": "weapon",
    "axe": "weapon",
    "machado": "weapon",
    "mace": "weapon",
    "maça": "weapon",
    "spear": "weapon",
    "lanca": "weapon",
    "lança": "weapon",
    "dagger": "weapon",
    "adaga": "weapon",
    "bow": "weapon",
    "arco": "weapon",
    "staff": "weapon",
    "cajado": "weapon",
    "shield": "weapon",
    "escudo": "weapon",
    "wand": "weapon",
    "varinha": "weapon",
    # tree
    "tree": "tree",
    "arvore": "tree",
    "árvore": "tree",
    "pine": "tree",
    "oak": "tree",
    "carvalho": "tree",
    "palmtree": "tree",
    "palm": "tree",
    "palmeira": "tree",
    # rock
    "rock": "rock",
    "rocha": "rock",
    "boulder": "rock",
    "pedra": "rock",
    "stone": "rock",
    # mineral
    "mineral": "mineral",
    "minério": "mineral",
    "mineri": "mineral",
    "crystal": "mineral",
    "cristal": "mineral",
    "gem": "mineral",
    "gema": "mineral",
    "ore": "mineral",
    "quartz": "mineral",
    "quartzo": "mineral",
    # building
    "building": "building",
    "edificio": "building",
    "edifício": "building",
    "house": "building",
    "casa": "building",
    "castle": "building",
    "castelo": "building",
    "tower": "building",
    "torre": "building",
    "wall": "building",
    "muro": "building",
    "ruins": "building",
    "ruinas": "building",
    "ruínas": "building",
    # furniture
    "furniture": "furniture",
    "movel": "furniture",
    "móvel": "furniture",
    "table": "furniture",
    "mesa": "furniture",
    "chair": "furniture",
    "cadeira": "furniture",
    "bed": "furniture",
    "cama": "furniture",
    "shelf": "furniture",
    "prateleira": "furniture",
    "bench": "furniture",
    "banco": "furniture",
    "throne": "furniture",
    "trono": "furniture",
    # vegetation
    "vegetation": "vegetation",
    "vegetacao": "vegetation",
    "vegetação": "vegetation",
    "bush": "vegetation",
    "arbusto": "vegetation",
    "plant": "vegetation",
    "planta": "vegetation",
    "flower": "vegetation",
    "flor": "vegetation",
    "grass": "vegetation",
    "grama": "vegetation",
    "mushroom": "vegetation",
    "cogumelo": "vegetation",
    "fern": "vegetation",
    "samambaia": "vegetation",
    # vehicle
    "vehicle": "vehicle",
    "veiculo": "vehicle",
    "veículo": "vehicle",
    "cart": "vehicle",
    "carroca": "vehicle",
    "wagon": "vehicle",
    "carro": "vehicle",
    "boat": "vehicle",
    "barco": "vehicle",
    "ship": "vehicle",
    "navio": "vehicle",
    "carriage": "vehicle",
    "carruagem": "vehicle",
    # armor
    "armor": "armor",
    "armadura": "armor",
    "helmet": "armor",
    "elmo": "armor",
    "capacete": "armor",
    "gauntlet": "armor",
    "manopla": "armor",
    "breastplate": "armor",
    "peitoral": "armor",
    "pauldron": "armor",
    "brace": "armor",
    # food
    "food": "food",
    "comida": "food",
    "alimento": "food",
    "apple": "food",
    "maca": "food",
    "maçã": "food",
    "bread": "food",
    "pao": "food",
    "pão": "food",
    "potion": "food",
    "pocao": "food",
    "poção": "food",
    "meat": "food",
    "carne": "food",
    "fish": "food",
    "peixe": "food",
    "cheese": "food",
    "queijo": "food",
    # tool
    "tool": "tool",
    "ferramenta": "tool",
    "hammer": "tool",
    "martelo": "tool",
    "pickaxe": "tool",
    "picareta": "tool",
    "shovel": "tool",
    "pa": "tool",
    "hoe": "tool",
    "enxada": "tool",
    "rake": "tool",
    "ancinho": "tool",
    "torch": "tool",
    "tocha": "tool",
    "lantern": "tool",
    "lampada": "tool",
    "lâmpada": "tool",
    "key": "tool",
    "chave": "tool",
    "rope": "tool",
    "corda": "tool",
    "bucket": "tool",
    "balde": "tool",
    # terrain
    "terrain": "terrain",
    "terreno": "terrain",
    "ground": "terrain",
    "chao": "terrain",
    "chão": "terrain",
    "tile": "terrain",
    "azulejo": "terrain",
    "path": "terrain",
    "caminho": "terrain",
    "road": "terrain",
    "estrada": "terrain",
    # effects
    "effect": "effects",
    "efeito": "effects",
    "effects": "effects",
    "efeitos": "effects",
    "particle": "effects",
    "particula": "effects",
    "partícula": "effects",
    "fire": "effects",
    "fogo": "effects",
    "explosion": "effects",
    "explosao": "effects",
    "explosão": "effects",
    "magic": "effects",
    "magia": "effects",
    "aura": "effects",
    "sparkle": "effects",
    "faísca": "effects",
}


def get_category(name: str) -> AssetCategory | None:
    return CATEGORIES.get(name)


def list_categories() -> list[str]:
    return list(CATEGORIES.keys())


def infer_category(idea: str, kind: str) -> str:
    """Try to guess category from idea text + kind via keyword matching."""
    text = f"{idea} {kind}".lower()
    for keyword, cat_key in _KEYWORD_MAP.items():
        if keyword in text:
            return cat_key
    return ""


def get_target_faces(category: str, default: int = 3000, face_ratio: float = 1.0) -> int:
    cat = CATEGORIES.get(category)
    base = cat.target_faces if cat else default
    if face_ratio <= 0:
        return 0
    return max(4, int(base * face_ratio))
