// Viber procedural sky — perspetiva atmosférica, nuvens volumétricas
// (raymarch curto sobre um plano), disco solar com halo e godrays, lua
// com fases, estrelas em três camadas, via láctea, aurora e meteoros.
//
// O domo é uma esfera invertida centrada na câmara; a direção do fragmento é
// `normalize(world_position - view.world_from_view[3].xyz)`.
//
// DUAS VIAS DE CONFIGURAÇÃO
//   1. consts CONFIG abaixo — reescritas por `viber run` a partir do
//      `<Sky>`/`<DayCycle>`/`<Weather>` do mundo;
//   2. `sky` (uniform de material, group 2 binding 0) — a paleta da HORA,
//      escrita por `sky::sky_material_drive` a partir de `AtmosphereState`.
//      O relógio do mundo NÃO é `globals.time`: `set_clock` e o jogo mexem
//      em `DayCycleState`, e derivar a hora do tempo do motor punha o disco
//      solar no céu às 23:00.
//
// NOTA r1 (builder-ceu): a paleta da hora vinha por reescrita do MESMO
// asset `ShaderBuffer` via `set_data` — o asset CPU ficava com os bytes
// certos mas o binding lia lixo. Agora `sky_material_drive` publica um
// buffer NOVO por frame (path `Added`, o único que chegou à GPU nos
// testes). O struct é só `vec4`s: layout std430 sem surpresas.

#import bevy_render::view::View
#import bevy_render::globals::Globals
#import bevy_pbr::forward_io::VertexOutput

@group(0) @binding(0) var<uniform> view: View;
@group(0) @binding(11) var<uniform> globals: Globals;

struct SkyUniform {
    // xyz = direção para o sol, w = fator dia (1 dia, 0 noite)
    sun: vec4<f32>,
    // xyz = direção para a lua, w = fator noite
    moon: vec4<f32>,
    // rgb = cor do zénite, w = fator hora dourada
    zenith: vec4<f32>,
    // rgb = cor do horizonte, w = delta de cobertura do <Weather>
    horizon: vec4<f32>,
    // rgb = tinta do sol, w = tempo decorrido (s)
    sun_tint: vec4<f32>,
    // x,y = vento; z = reservado; w = minuto do dia
    params: vec4<f32>,
};

@group(2) @binding(0) var<storage, read> sky: SkyUniform;

// Ganho 1.0 (r7-r8 REVERTIDO): a exposição física da câmara vive no path
// PBR do StandardMaterial — este material custom NUNCA a recebe, pelo que
// a paleta 0..1 sai direta para o tonemap com gradiente visível. O ×400 do
// r7 empurrava tudo para TMc=1.0 (o "retângulo de branco").
const SKY_RADIANCE: f32 = 1.0;

// === WORLD CONFIG (generated by `viber run` — edit the XML, not this block) ===
const CFG_DRIVE: f32 = 0;
const CFG_CLOCK_START: f32 = 480;
const CFG_CLOCK_SPEED: f32 = 1.2;
const CFG_DAWN: f32 = 330;
const CFG_DUSK: f32 = 1170;
const CFG_MAX_ELEV: f32 = 62;
const CFG_AZ_BASE: f32 = 205;
const CFG_SUN_ELEV: f32 = 17;
const CFG_SUN_AZ: f32 = 205;
const CFG_MIE: f32 = 0.0035;
const CFG_MIE_G: f32 = 0.8;
const CFG_SUN_INTENSITY: f32 = 2.6;
const CFG_CLOUD_COVERAGE: f32 = 0.45;
const CFG_CLOUD_DENSITY: f32 = 0.32;
const CFG_CLOUD_ELEVATION: f32 = 0.55;
const CFG_STAR_DENSITY: f32 = 1;
const CFG_AURORA: f32 = 0.6;
const CFG_NEBULA: f32 = 0.5;
const CFG_WIND_X: f32 = 0.7;
const CFG_WIND_Z: f32 = 0.25;
// === END WORLD CONFIG ===

const PI: f32 = 3.141592653589793;

// ── Noise helpers ────────────────────────────────────────────────────
fn hash21(p: vec2<f32>) -> f32 {
    var q = fract(p * vec2(123.34, 456.21));
    q += dot(q, q + 45.32);
    return fract(q.x * q.y);
}

fn hash31(p: vec3<f32>) -> f32 {
    var q = fract(p * 0.1031);
    q += dot(q, q.yzx + 33.33);
    return fract((q.x + q.y) * q.z);
}

fn value_noise(p: vec2<f32>) -> f32 {
    let i = floor(p);
    let f = fract(p);
    let u = f * f * (3.0 - 2.0 * f);
    let a = hash21(i);
    let b = hash21(i + vec2(1.0, 0.0));
    let c = hash21(i + vec2(0.0, 1.0));
    let d = hash21(i + vec2(1.0, 1.0));
    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

// Rotação de domínio por oitava: sem ela as oitavas alinham-se à grelha do
// value noise e as nuvens ganham artefactos quadrados axis-aligned.
const ROT: mat2x2<f32> = mat2x2<f32>(0.737, 0.676, -0.676, 0.737);

fn fbm5(p: vec2<f32>) -> f32 {
    var v = 0.0;
    var amp = 0.5;
    var pp = p;
    for (var i = 0; i < 5; i++) {
        v += amp * value_noise(pp);
        pp = ROT * pp * 2.03 + vec2(11.7, 5.3);
        amp *= 0.5;
    }
    return v;
}

fn fbm3(p: vec2<f32>) -> f32 {
    var v = 0.0;
    var amp = 0.5;
    var pp = p;
    for (var i = 0; i < 3; i++) {
        v += amp * value_noise(pp);
        pp = ROT * pp * 2.03 + vec2(11.7, 5.3);
        amp *= 0.5;
    }
    return v;
}

// ── Gradiente atmosférico ────────────────────────────────────────────
//
// A paleta (zénite/horizonte) vem do CPU já resolvida para a hora, por isso
// esta função é só a FORMA da transição — e a forma é o que separa um céu
// chapado de um céu com ar dentro:
//
//   * expoente alto perto do horizonte → a banda pálida fica FINA e o azul
//     domina a maior parte do enquadramento (as referências têm o horizonte
//     quase branco só nos últimos graus);
//   * uma segunda banda, larga e quente, centrada no azimute do sol, que
//     abre o pôr-do-sol para meio céu em vez de um risco no horizonte.
fn sky_gradient(up: f32, toward_sun: f32) -> vec3<f32> {
    let zenith = sky.zenith.rgb;
    let horizon = sky.horizon.rgb;
    let golden = sky.zenith.w;

    let t = pow(clamp(1.0 - abs(up), 0.0, 1.0), 3.4);
    var color = mix(zenith, horizon, t);

    // Abaixo da linha do horizonte o domo escurece para o chão. A rampa é
    // LARGA de propósito: com a transição curta (−0.25→0.02) o degradê
    // ganhava um anel claro colado a um anel escuro e lia-se como um aro de
    // néon à volta do mundo sempre que a câmara subia o pitch.
    color *= mix(0.62, 1.0, smoothstep(-0.55, 0.10, up));

    // GOLDEN RING 360° (r15): o entardecer esquenta TODO o anel do horizonte
    // E o meio-céu (azimute-independente — o pôr-do-sol do BOTW é um
    // gradiente de 360°: dourado-rosado em todas as direções, zénite azul).
    // O sol adiciona apenas o EXTRA no seu setor (banda, abaixo).
    let ring = pow(clamp(1.0 - abs(up), 0.0, 1.0), 0.75);
    let warm = sky.sun_tint.rgb * vec3(1.0, 0.84, 0.68);
    color = mix(color, warm, ring * golden * 0.45);

    // Banda quente à volta do sol: larga na horizontal, curta na vertical.
    // Na hora dourada a banda abre e satura — é ela que "estoura" o pôr-do-sol.
    let band = pow(clamp(1.0 - abs(up), 0.0, 1.0), 1.4) * pow(toward_sun, 2.0);
    color = mix(color, sky.sun_tint.rgb * mix(0.55, 1.05, golden), band * golden);

    // Névoa junto ao horizonte — é ela que faz a serra distante "descolar"
    // do céu. Expoente moderado (8) e SEM ganho acima do horizonte: com 14 e
    // ×1.05 saía uma fita brilhante em vez de um degradê.
    let haze = pow(clamp(1.0 - abs(up), 0.0, 1.0), 8.0);
    color = mix(color, horizon, haze * 0.55);
    return color;
}

// ── Sol: disco, halo de Mie e godrays radiais ────────────────────────
fn sun_light(dir: vec3<f32>, sun: vec3<f32>) -> vec3<f32> {
    let day = sky.sun.w;
    let golden = sky.zenith.w;
    let d = clamp(dot(dir, sun), 0.0, 1.0);
    // O disco continua a ler-se com o sol a raspar o horizonte (é o que
    // "estoura" o pôr-do-sol nas referências).
    let disc = smoothstep(0.99940, 0.99972, d);
    // Halo de Mie: com o sol baixo o glow ABRE (exponente desce) e ganha
    // força — é o "sol derretido" da golden hour nas referências BOTW.
    let glow_pow = mix(1400.0, 260.0, clamp(CFG_MIE_G, 0.0, 1.0)) * mix(1.0, 0.45, golden);
    let glow = pow(d, glow_pow);
    let halo = pow(d, 5.0) * (0.16 + 0.22 * golden) + pow(d, 22.0) * (0.24 + 0.34 * golden);
    let tint = sky.sun_tint.rgb;

    // Godrays: leque radial à volta do sol, animado devagar. Barato (um
    // atan2 + um seno) e só acende perto do disco, por isso não sujeita o
    // resto do céu.
    let up_ref = normalize(cross(sun, vec3(0.0, 1.0, 0.0)) + vec3(1e-4));
    let side = cross(sun, up_ref);
    let angle = atan2(dot(dir, side), dot(dir, up_ref));
    let rays = pow(d, 40.0)
        * (0.55 + 0.45 * sin(angle * 9.0 + sky.sun_tint.w * 0.05))
        * (0.5 + 0.5 * sin(angle * 23.0 - sky.sun_tint.w * 0.03));

    let above = smoothstep(-0.06, 0.06, sun.y);
    let lit = clamp(day + golden, 0.0, 1.0);
    // O disco fica MUITO acima do céu (~400) e do terreno iluminado (~2500):
    // é ele que tem de passar o threshold do bloom e ler como SOL.
    return tint
        * (disc * 24.0 + (glow * CFG_MIE * 620.0 + halo + rays * 0.55) * lit)
        * CFG_SUN_INTENSITY
        * above;
}

// ── Lua: disco com fase, mares e halo ────────────────────────────────
fn moon_light(dir: vec3<f32>, moon: vec3<f32>, night: f32) -> vec3<f32> {
    if (night < 0.02) {
        return vec3(0.0);
    }
    let md = clamp(dot(dir, moon), 0.0, 1.0);
    // Disco grande (as referências noturnas têm uma lua que se vê mesmo).
    let disc = smoothstep(0.99930, 0.99962, md);
    // Halo mais presente: é o que faz a lua "brilhar" em vez de ser um
    // autocolante branco no céu (contraste de fontes à noite).
    let halo = pow(md, 900.0) * 0.70 + pow(md, 90.0) * 0.24 + pow(md, 14.0) * 0.08;
    let moon_col = vec3(0.95, 0.96, 1.0);

    let t1 = normalize(cross(moon, vec3(0.0, 1.0, 0.0)) + vec3(1e-4));
    let t2 = cross(moon, t1);
    let local = vec2(dot(dir, t1), dot(dir, t2));

    // Mares lunares: manchas grandes de baixo contraste no plano do disco.
    let uv = local * 210.0;
    let maria = value_noise(uv * 1.3) * 0.6 + value_noise(uv * 3.1) * 0.4;
    // Fase: um terminador suave que avança ~1/8 por dia de jogo.
    let phase = cos(sky.params.w * 0.0043 + 1.1);
    let terminator = smoothstep(-0.35, 0.35, local.x * 260.0 - phase * 0.85);
    // Earthshine: a parte escura fica legível em vez de desaparecer.
    let surface = disc * (0.72 + 0.42 * maria) * mix(0.16, 1.0, terminator);

    return (surface * moon_col * 2.4 + halo * moon_col) * night;
}

// ── Estrelas + via láctea ────────────────────────────────────────────
fn star_layer(dir: vec3<f32>, scale: f32, threshold: f32, brightness: f32, time: f32) -> vec3<f32> {
    let sp = dir * scale;
    let cell = floor(sp);
    let h = hash31(cell);
    let lit = step(threshold, h);
    // A estrela vive no centro da célula: sem isto a "estrela" é a célula
    // inteira e o céu ganha um xadrez de quadrados acesos.
    let local = fract(sp) - 0.5;
    let point = exp(-dot(local, local) * 42.0);
    let twinkle = 0.6 + 0.4 * sin(time * 2.0 + h * 40.0);
    let tint = mix(vec3(0.72, 0.82, 1.0), vec3(1.0, 0.86, 0.7), hash31(cell + vec3<f32>(7.0)));
    return tint * lit * point * twinkle * brightness;
}

fn star_field(dir: vec3<f32>, time: f32, night: f32) -> vec3<f32> {
    if (night < 0.02) {
        return vec3(0.0);
    }
    // Estrelas mais presentes: à distância de câmara de jogo, abaixo disto
    // o céu noturno lê-se como "preto com ruído" em vez de céu estrelado.
    let dim = star_layer(dir, 170.0, 0.9950, 0.85 * CFG_STAR_DENSITY, time);
    let mid = star_layer(dir, 96.0, 0.9965, 1.60 * CFG_STAR_DENSITY, time);
    let bright = star_layer(dir, 52.0, 0.9980, 3.2 * CFG_STAR_DENSITY, time);
    // As estrelas desaparecem junto ao horizonte (extinção atmosférica).
    let extinction = smoothstep(-0.02, 0.30, dir.y);
    return (dim + mid + bright) * night * extinction;
}

// Via láctea: uma faixa larga de poeira estelar num grande círculo inclinado.
// (inativa no caminho de composição — mantida para reativação rápida)
fn milky_way(dir: vec3<f32>, night: f32) -> vec3<f32> {
    if (night < 0.05 || CFG_NEBULA < 0.001) {
        return vec3(0.0);
    }
    let axis = normalize(vec3(0.42, 0.62, -0.66));
    let band = 1.0 - abs(dot(dir, axis));
    // Núcleo mais apertado e fraco (r4): a faixa larga ×bloom lia-se como
    // uma mancha magenta estourada no terço superior do frame noturno.
    let core = pow(clamp(band, 0.0, 1.0), 34.0);
    let n = fbm3(dir.xz * 3.4 + vec2(dir.y * 4.0, 0.0));
    let dust = mix(0.35, 1.0, n);
    let mask = core * dust * night * smoothstep(0.0, 0.28, dir.y);
    return mix(vec3(0.20, 0.17, 0.34), vec3(0.42, 0.45, 0.62), n) * mask * CFG_NEBULA * 0.55;
}

// ── Aurora ───────────────────────────────────────────────────────────
// (inativa no caminho de composição — mantida para reativação rápida)
fn aurora_ribbons(dir: vec3<f32>, time: f32, night: f32) -> vec3<f32> {
    if (night < 0.05 || CFG_AURORA < 0.001) {
        return vec3(0.0);
    }
    let wind = vec2(sky.params.x, sky.params.y);
    let auv = dir.xz * 1.3 + wind * time * 0.02;
    let a1 = fbm3(auv * 0.7 + vec2(time * 0.008, 0.0));
    let band_y = 0.34 + (a1 - 0.5) * 0.30;
    let band = exp(-pow((dir.y - band_y) * 6.0, 2.0));
    let curtains = fbm3(vec2(auv.x * 2.6 + time * 0.02, dir.y * 5.0));
    let a = band * smoothstep(0.50, 0.80, curtains) * CFG_AURORA * night
        * smoothstep(0.08, 0.25, dir.y);
    return mix(vec3(0.15, 0.85, 0.45), vec3(0.30, 0.55, 0.95), curtains) * a * 0.28;
}

// ── Meteoro ──────────────────────────────────────────────────────────
// (inativa no caminho de composição — mantida para reativação rápida)
fn meteor(dir: vec3<f32>, time: f32, night: f32) -> vec3<f32> {
    if (night < 0.25) {
        return vec3(0.0);
    }
    let win = floor(time / 11.0);
    if (hash21(vec2(win * 0.173, 4.7)) < 0.5) {
        return vec3(0.0);
    }
    let ph = fract(time / 11.0);
    let life = smoothstep(0.05, 0.12, ph) * (1.0 - smoothstep(0.12, 0.20, ph));
    if (life <= 0.0) {
        return vec3(0.0);
    }
    let sx = hash21(vec2(win, 1.3)) * 2.0 - 1.0;
    let sz = hash21(vec2(win, 2.7)) * 2.0 - 1.0;
    let start = normalize(vec3(sx, 0.55 + 0.35 * hash21(vec2(win, 5.1)), sz));
    let vel = normalize(cross(start, vec3(0.0, 0.3, 1.0)) + vec3(0.001));
    let head = normalize(start + vel * (ph * 3.0 - 0.3));
    let tail = normalize(head - vel * 0.02);
    let streak = exp(-(1.0 - dot(dir, head)) * 260.0)
        + exp(-(1.0 - dot(dir, tail)) * 150.0) * 0.35;
    return vec3(0.9, 0.95, 1.0) * streak * life * night * 2.2;
}

// ── Nuvens ───────────────────────────────────────────────────────────
//
// As nuvens do baseline eram "pontinhos" por duas razões: a projeção ao
// plano multiplicava o uv por 3 (células pequenas) e a única amostra de FBM
// dava uma mancha plana sem interior. Aqui:
//
//   * `CLOUD_SCALE` desce a frequência ~4× — cada cúmulo ocupa uma boa
//     fração do enquadramento, como nas referências;
//   * a densidade é integrada em TRÊS alturas do plano (um raymarch muito
//     curto): a base vê mais nuvem que o topo, o que dá volume real em vez
//     de um recorte;
//   * a auto-sombra vem de uma amostra deslocada NA DIREÇÃO DO SOL, com o
//     silver lining a acender só a borda virada a ele.

// Nuvens GRANDES: a frequência baixa (0.55) põe cada cúmulo a ocupar um
// quarteirão do céu — nuvens pequenas demais leem-se como "ruído" e matam
// a presença do céu (o gap do baseline).
const CLOUD_SCALE: f32 = 0.55;

fn cloud_uv(dir: vec3<f32>, height: f32, time: f32) -> vec2<f32> {
    let wind = vec2(sky.params.x, sky.params.y);
    // Projeção ao plano das nuvens; perto do zénite a projeção colapsa, por
    // isso mistura-se com o mapa tangencial.
    let plane = dir.xz / (dir.y + 0.10) * CLOUD_SCALE * height;
    let tangential = dir.xz * CLOUD_SCALE * 1.4;
    return mix(plane, tangential, smoothstep(0.55, 0.95, dir.y)) + wind * time * 0.004;
}

fn cloud_density(uv: vec2<f32>, threshold: f32) -> f32 {
    let n = fbm5(uv);
    return smoothstep(threshold, threshold + 0.22, n);
}

fn cumulus_layer(
    dir: vec3<f32>,
    color: vec3<f32>,
    time: f32,
    sun_az: vec2<f32>,
    toward_sun: f32,
) -> vec3<f32> {
    if (dir.y <= 0.008) {
        return color;
    }
    let day = sky.sun.w;
    let golden = sky.zenith.w;
    // +golden×0.10: no money shot da golden hour o céu tem de ter nuvens
    // lendo CONTRA o gradiente quente (r14) — céu vazio = diorama.
    let coverage = clamp(CFG_CLOUD_COVERAGE + sky.horizon.w + golden * 0.10, 0.0, 1.0);
    // O `fbm5` vive à volta de 0.5 com cauda até ~0.8: com o limiar antigo
    // (0.78→0.36) uma cobertura de 0.45 pedia n > 0.59, ou seja só o topo da
    // cauda passava — daí o "céu vazio" das rondas anteriores. Esta janela
    // põe a cobertura autoral em cima da mediana do ruído, que é o que faz
    // cúmulos GRANDES ocuparem parte real do enquadramento sem fechar o céu.
    let threshold = mix(0.70, 0.32, coverage);
    let base_height = mix(0.7, 2.4, CFG_CLOUD_ELEVATION);

    // Raymarch de 3 passos entre a base e o topo do estrato: a diferença de
    // paralaxe entre as camadas é o que lê como VOLUME.
    let uv0 = cloud_uv(dir, base_height, time);
    let uv1 = cloud_uv(dir, base_height * 1.16, time);
    let uv2 = cloud_uv(dir, base_height * 1.34, time);
    let d0 = cloud_density(uv0, threshold);
    let d1 = cloud_density(uv1, threshold);
    let d2 = cloud_density(uv2, threshold);
    let cov = (d0 + d1 + d2) / 3.0;
    // Fade no horizonte: sem ele o plano projetado vira um risco duro.
    let alpha = cov
        * mix(0.55, 1.0, clamp(CFG_CLOUD_DENSITY + 0.5, 0.0, 1.0))
        * smoothstep(0.008, 0.09, dir.y);
    if (alpha <= 0.002) {
        return color;
    }

    // Auto-sombra: a base (d0) mais densa que o topo (d2) = interior escuro;
    // uma amostra deslocada ao sol acende o lado virado a ele.
    let lit = cloud_density(uv2 + sun_az * 0.55, threshold);
    let occlusion = clamp(d0 - d2, -1.0, 1.0);
    var shade = 0.52 + 0.55 * (lit - occlusion * 0.9);

    // Cor: branca em cima, sombra a puxar ao azul do zénite, e ao pôr-do-sol
    // a base ganha um toque quente (sem saturar para mauve — sombras de
    // nuvem saturadas lêem-se como "sujidade" na hora dourada).
    let lit_col = mix(vec3(1.02, 1.01, 1.00), sky.sun_tint.rgb * 0.95, golden * 0.70);
    let shadow_col = mix(sky.zenith.rgb * 1.5 + vec3(0.16), vec3(0.40, 0.27, 0.34), golden * 0.65);
    var cloud_col = mix(shadow_col, lit_col, clamp(shade, 0.0, 1.0));
    // Corpo comprimido na golden hour: contra o céu dourado a forma lê-se
    // pela DIFERENÇA para o fundo, não por brilho absoluto.
    cloud_col *= mix(1.0, 0.80, golden);

    // Silver lining: só a borda fina virada ao sol.
    let rim = smoothstep(0.16, 0.0, abs(cov - 0.5)) * pow(toward_sun, 3.0);
    cloud_col += sky.sun_tint.rgb * rim * (0.35 + 0.9 * golden) * day;

    // À noite as nuvens são silhuetas QUASE pretas (r5): corpos cinza-azuis
    // empilhavam com os fenómenos e estouravam o terço superior do frame.
    cloud_col = mix(cloud_col * vec3(0.05, 0.07, 0.12), cloud_col, day);

    return mix(color, cloud_col, clamp(alpha, 0.0, 1.0));
}

// Cirros: camada alta, fina e alongada pelo vento — a "textura" do céu alto.
fn cirrus_layer(dir: vec3<f32>, color: vec3<f32>, time: f32) -> vec3<f32> {
    if (dir.y <= 0.12) {
        return color;
    }
    let day = sky.sun.w;
    let golden = sky.zenith.w;
    let base = cloud_uv(dir, 1.7, time * 0.6);
    let stretched = vec2(base.x * 0.45 - base.y * 0.20, base.y * 2.4);
    let n = fbm3(stretched * 1.1);
    let alpha = smoothstep(0.50, 0.82, n) * 0.13 * (0.25 + 0.75 * day)
        * smoothstep(0.12, 0.42, dir.y);
    let cirrus_col = mix(
        mix(vec3(0.30, 0.36, 0.55), vec3(1.0, 0.99, 0.97), day),
        sky.sun_tint.rgb * 1.2,
        golden * 0.8,
    );
    return mix(color, cirrus_col, clamp(alpha, 0.0, 1.0));
}

@fragment
fn fragment(mesh: VertexOutput) -> @location(0) vec4<f32> {
    let cam_pos = view.world_from_view[3].xyz;
    let dir = normalize(mesh.world_position.xyz - cam_pos);
    let up = clamp(dir.y, -1.0, 1.0);

    let sun = normalize(sky.sun.xyz + vec3(1e-6, 0.0, 0.0));
    let moon = normalize(sky.moon.xyz + vec3(1e-6, 0.0, 0.0));
    let day = sky.sun.w;
    let night = sky.moon.w;
    let time = sky.sun_tint.w;

    let sun_az = normalize(vec2(sun.x, sun.z) + vec2(1e-5));
    let dir_az = normalize(vec2(dir.x, dir.z) + vec2(1e-5));
    let toward_sun = max(dot(dir_az, sun_az), 0.0);

    // Céu → astros → nuvens. Em radiância da cena (ver SKY_RADIANCE) para
    // sobreviver à exposição física da câmara.
    //
    // r8: milky_way/aurora_ribbons/meteor REMOVIDOS do caminho ativo — à
    // noite empilhavam violeta/verde/branco sobre meio céu e liam-se como
    // "crepúsculo cinzento" (o alvo do BOTW é gradiente azul + estrelas +
    // lua). As funções ficam abaixo para referência/reaativação.
    var color = sky_gradient(up, toward_sun);
    color += star_field(dir, time, night);
    color += moon_light(dir, moon, night);
    color += sun_light(dir, sun);
    color = cumulus_layer(dir, color, time, sun_az, toward_sun);
    color = cirrus_layer(dir, color, time);

    return vec4(color * SKY_RADIANCE, 1.0);
}
