// Viber terrain chunk materials — 4 simultaneous ground layers per chunk.
//
// Each terrain chunk carries its OWN material: the four pool textures with
// the highest aggregate weight in that chunk + one RGBA8 splat plane baked
// per chunk (weights renormalized to sum 1). Areas of the world can render
// completely different layer sets — the old single-material design bound 13
// layers + 4 global splat planes (34 bindings) and crashed the NVIDIA
// driver's pipeline-layout path (SIGSEGV inside libnvidia-gpucomp), while a
// chunk material binds 5 textures + 1 uniform and stays well clear of it.
//
// WORLD SPECIALIZATION: `viber run` rewrites the CONFIG block below from the
// `<Terrain>` spec before the renderer loads this file (NO material uniform
// for world constants — same architecture as sky.wgsl/water.wgsl).
//
// BINDINGS (merged material bind group, `@group(#{MATERIAL_BIND_GROUP})`,
// StandardMaterial occupies 0–30): layer i binds texture 40+2i / sampler
// 41+2i (i in 0..4 — the 4th pair is the chunk's splat plane at 48/49) and
// the per-chunk style/placement table rides a uniform at 50.

#import bevy_pbr::forward_io::{VertexOutput, FragmentOutput}
#import bevy_pbr::pbr_fragment::pbr_input_from_standard_material
#import bevy_pbr::pbr_functions::{apply_pbr_lighting, main_pass_post_lighting_processing}
#import bevy_pbr::mesh_view_bindings::view

// === WORLD CONFIG (generated by `viber run` — edit the XML, not this block) ===
const CFG_TRI_SLOPE: f32 = 0.35721236;
const CFG_TRI_SOFT: f32 = 0.12;
const CFG_STRATA_SPACING: f32 = 4;
const CFG_STRATA_STRENGTH: f32 = 0.25;
// === END WORLD CONFIG ===

// Per-chunk layer table. `tiles[i].x` is the tile size in meters of layer i,
// `tints/flats/roughs` its photographic-color correction, flat far color and
// perceptual roughness; `chunk` places the plane: xy = origin XZ, z = edge
// size, w = index (0..3) of the rock layer for the triplanar walls, -1 = off.
struct TerrainChunkParams {
    tiles: array<vec4<f32>, 4>,
    tints: array<vec4<f32>, 4>,
    flats: array<vec4<f32>, 4>,
    roughs: array<vec4<f32>, 4>,
    chunk: vec4<f32>,
};

@group(#{MATERIAL_BIND_GROUP}) @binding(40) var layer0: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(41) var layer0_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(42) var layer1: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(43) var layer1_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(44) var layer2: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(45) var layer2_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(46) var layer3: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(47) var layer3_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(200) var splat: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(201) var splat_sampler: sampler;

// Achatamento por distância: perto vê-se o material, longe vê-se cor. FLAT_MIN
// é o achatamento mínimo colado à câmara — as fotos do pool têm contraste a
// mais para um mundo cel-ish mesmo aos pés do herói.
const FLAT_NEAR: f32 = 42.0;
const FLAT_FAR: f32 = 260.0;
const FLAT_MIN: f32 = 0.22;

// Weights below this contribute nothing visible; skipping their texture
// fetch keeps the typical fragment at 2–3 layers instead of 4.
const WEIGHT_EPSILON: f32 = 0.004;

// Rock layer fetch for the triplanar walls — bindings cannot be indexed, so
// the uniform-chosen layer is picked by explicit branches (uniform control
// flow; gradient sampling stays legal).
fn layer_sample(index: i32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec3<f32> {
    if (index == 0) {
        return textureSampleGrad(layer0, layer0_sampler, uv, dx, dy).rgb;
    }
    if (index == 1) {
        return textureSampleGrad(layer1, layer1_sampler, uv, dx, dy).rgb;
    }
    if (index == 2) {
        return textureSampleGrad(layer2, layer2_sampler, uv, dx, dy).rgb;
    }
    return textureSampleGrad(layer3, layer3_sampler, uv, dx, dy).rgb;
}

@fragment
fn fragment(in: VertexOutput) -> FragmentOutput {
    // T5: material próprio UNLIT — só a splat
    let local = fract(in.world_position.xz / 64.0);
    let s = textureSampleGrad(splat, splat_sampler, local, dpdx(local), dpdy(local));
    var out: FragmentOutput;
    out.color = vec4<f32>(s.rgb, 1.0);
    return out;
}
