// Viber water — animated lake/river surface with depth-based volume, on top
// of the full PBR stack.
//
// The fragment entry REPLACES `StandardMaterial`'s (ExtendedMaterial base):
// it rebuilds `PbrInput` via `pbr_input_from_standard_material`, perturbs the
// normal with a wind-driven wave field, and — the part that makes water read
// as a *body* instead of a sheet of cellophane — reconstructs the opaque
// scene behind the surface from the DEPTH PREPASS to get the real water
// column, then applies Beer–Lambert absorption over it. Shallow water is
// clear, deep water is near-opaque, and the shoreline gets a foam band for
// free. Lighting, shadows and fog still come from the normal PBR path.
//
// MESH CONTRACT (see `water.rs`): vertex COLOR = body rgb + shore-fade mask
// in alpha; vertex UV.x = the body's `opacity` reinterpreted as an
// **extinction scale** (how murky the water is), UV.y = radial/cross-stream
// coordinate. No texture is sampled, so UV.x is free for this.
//
// WORLD SPECIALIZATION: `viber run` rewrites the CONFIG block below from the
// world's <DayCycle>/<Weather> attributes before the renderer loads this file
// (mirror of shaders/sky.wgsl — NO material uniform: the Bevy 0.19 slot-1
// storage promotion never re-uploads modified uniforms). Per-frame values
// come from `Globals` (engine-updated view binding).

#import bevy_pbr::forward_io::{VertexOutput, FragmentOutput}
#import bevy_pbr::pbr_fragment::pbr_input_from_standard_material
#import bevy_pbr::pbr_functions::{alpha_discard, apply_pbr_lighting, main_pass_post_lighting_processing}
// O `globals`/`view` chegam pelo mesh_view_bindings (o pbr_fragment importa-o)
// — redeclarar em group(0) conflitua com o binding da view.
#import bevy_pbr::mesh_view_bindings::{globals, view}
#import bevy_pbr::view_transformations as vt
// `prepass_depth` só existe com DEPTH_PREPASS; o módulo importa-se sempre
// (fica vazio sem o define) e a CHAMADA é que vai dentro do #ifdef.
#import bevy_pbr::prepass_utils

// === WORLD CONFIG (generated by `viber run` — edit the XML, not this block) ===
const CFG_DRIVE: f32 = 0;
const CFG_CLOCK_START: f32 = 480;
const CFG_CLOCK_SPEED: f32 = 1.2;
const CFG_DAWN: f32 = 330;
const CFG_DUSK: f32 = 1170;
const CFG_MAX_ELEV: f32 = 62;
const CFG_MIN_ELEV: f32 = 8;
const CFG_AZ_BASE: f32 = 205;
const CFG_SUN_ELEV: f32 = 17;
const CFG_SUN_AZ: f32 = 205;
const CFG_WIND_X: f32 = 0.7;
const CFG_WIND_Z: f32 = 0.25;
const CFG_WIND_STRENGTH: f32 = 1.5;
const CFG_WAVE_AMP: f32 = 1;
// === END WORLD CONFIG ===

// ── Volume ───────────────────────────────────────────────────────────
// Extinção por metro de coluna (Beer–Lambert). O vermelho morre primeiro,
// que é o que dá o desvio azul-esverdeado com a profundidade em vez de um
// simples escurecer. Multiplicada pela `opacity` do corpo (uv.x).
const EXTINCTION: vec3<f32> = vec3<f32>(0.90, 0.44, 0.30);
/// Comprimento máximo de coluna considerado (m) — evita `inf` quando o
/// prepass não escreveu nada atrás da água (céu).
const MAX_PATH: f32 = 60.0;
/// Banda de espuma junto à margem (profundidade vertical, m).
const FOAM_DEPTH: f32 = 0.45;
/// Profundidade em que a lâmina começa a existir (m) — abaixo disto a água
/// desaparece em vez de terminar numa linha dura sobre a margem.
const SHORE_FADE: f32 = 0.30;

// ── Noise helpers ────────────────────────────────────────────────────
// Hash INTEIRO sobre o índice de célula. O hash float clássico
// (`fract(p * vec2(123.34, 456.21))`) colapsa em coordenadas de mundo
// grandes: num mapa de 4 km, `x·123.34` chega a ~2.5e5, onde o espaçamento
// do f32 já é ~0.015 — o `fract` fica com uma mão-cheia de valores distintos
// e o ruído degenera em degraus rectos. Eram essas as faixas alinhadas que
// se viam a atravessar o lago. Aritmética u32 não tem esse problema.
fn hash21(p: vec2<f32>) -> f32 {
    let q = vec2<i32>(floor(p));
    var h = bitcast<u32>(q.x) * 0x27d4eb2du ^ bitcast<u32>(q.y) * 0x165667b1u;
    h = (h ^ (h >> 15u)) * 0x2c1b3c6du;
    h = (h ^ (h >> 13u)) * 0x297a2d39u;
    h = h ^ (h >> 16u);
    return f32(h & 0x00ffffffu) * (1.0 / 16777216.0);
}

fn value_noise(p: vec2<f32>) -> f32 {
    let i = floor(p);
    let f = fract(p);
    // Quintic (smootherstep): a cúbica do smoothstep deixa a derivada
    // descontínua na fronteira da célula, e é ESSA descontinuidade que
    // aparecia como a grelha de quadrados na lâmina de água.
    let u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    let a = hash21(i);
    let b = hash21(i + vec2(1.0, 0.0));
    let c = hash21(i + vec2(0.0, 1.0));
    let d = hash21(i + vec2(1.0, 1.0));
    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

/// FBM com rotação por oitava — sem a rotação todas as oitavas partilham os
/// eixos da grelha do `value_noise` e somam-se em xadrez alinhado a XZ.
fn fbm(p: vec2<f32>, drift: vec2<f32>) -> f32 {
    let rot = mat2x2<f32>(0.80, 0.60, -0.60, 0.80);
    var q = p;
    var amp = 0.5;
    var sum = 0.0;
    var norm = 0.0;
    for (var i = 0; i < 4; i += 1) {
        sum += (value_noise(q + drift * (1.0 + f32(i) * 0.35)) - 0.5) * amp;
        norm += amp;
        q = rot * q * 2.03 + vec2(11.7, 5.3);
        amp *= 0.5;
    }
    return sum / norm;
}

// ── Day clock (mirror of `worldsys::sun_drive` / shaders/sky.wgsl) ───
const PI: f32 = 3.141592653589793;
const MOON_ELEVATION_DEG: f32 = 52.0;

fn sun_elevation_deg(minute: f32, dawn: f32, dusk: f32, max_elevation: f32) -> f32 {
    if (minute >= dawn && minute < dusk) {
        let t = (minute - dawn) / (dusk - dawn);
        return sin(PI * t) * max_elevation;
    }
    let dusk_len = 24.0 * 60.0 - dusk + dawn;
    var t = (minute - dusk) / dusk_len;
    if (minute < dusk) {
        t = (minute + (24.0 * 60.0 - dusk)) / dusk_len;
    }
    return -abs(sin(PI * t)) * 25.0;
}

fn sun_azimuth_deg(minute: f32, dawn: f32, dusk: f32, base: f32) -> f32 {
    if (minute >= dawn && minute < dusk) {
        return base + 180.0 * (minute - dawn) / (dusk - dawn);
    }
    let dusk_len = 24.0 * 60.0 - dusk + dawn;
    var t = (minute - dusk) / dusk_len;
    if (minute < dusk) {
        t = (minute + (24.0 * 60.0 - dusk)) / dusk_len;
    }
    return base + 180.0 + 180.0 * t;
}

// Unit direction TOWARDS the sun/moon (world, Y-up) — same convention as
// `worldsys::sky_direction`, so the glint tracks the real directional light.
fn sky_direction(elevation_deg: f32, azimuth_deg: f32) -> vec3<f32> {
    let el = radians(elevation_deg);
    let az = radians(azimuth_deg);
    return normalize(vec3<f32>(cos(el) * sin(az), sin(el), cos(el) * cos(az)));
}

// ── Wave field ───────────────────────────────────────────────────────
// Quatro trens direccionais com direcções NÃO ortogonais e comprimentos de
// onda incomensuráveis (7.0 / 4.6 / 3.0 / 1.85 m) mais um FBM à deriva. A
// versão anterior somava três senos em ±wind/±perp com λ ≈ 11–30 m: as
// cristas alinhavam-se em duas famílias perpendiculares e liam-se como o
// xadrez de faixas rectas sobre o lago.
fn wave_height(p: vec2<f32>, t: f32) -> f32 {
    let wind = vec2<f32>(CFG_WIND_X, CFG_WIND_Z);
    let wdir = normalize(wind + vec2(1e-4, 0.0));
    let strength = clamp(CFG_WIND_STRENGTH, 0.05, 3.0);
    let speed = 0.55 + 0.45 * strength;

    // Direcções giradas em relação ao vento (graus): 0, +34, -51, +73.
    let d0 = wdir;
    let d1 = vec2<f32>(wdir.x * 0.829 - wdir.y * 0.559, wdir.x * 0.559 + wdir.y * 0.829);
    let d2 = vec2<f32>(wdir.x * 0.629 + wdir.y * 0.777, -wdir.x * 0.777 + wdir.y * 0.629);
    let d3 = vec2<f32>(wdir.x * 0.292 - wdir.y * 0.956, wdir.x * 0.956 + wdir.y * 0.292);

    // k = 2π/λ; dispersão de águas profundas: ω ∝ √k (cristas curtas correm
    // mais devagar, o campo nunca "congela" num padrão repetido).
    let k0 = 0.897; let k1 = 1.366; let k2 = 2.094; let k3 = 3.396;
    var h = 0.0;
    h += sin(dot(p, d0) * k0 - t * sqrt(k0) * 1.35 * speed) * 0.30;
    h += sin(dot(p, d1) * k1 + t * sqrt(k1) * 1.10 * speed) * 0.20;
    h += sin(dot(p, d2) * k2 - t * sqrt(k2) * 0.95 * speed) * 0.12;
    h += sin(dot(p, d3) * k3 + t * sqrt(k3) * 0.80 * speed) * 0.07;

    let drift = wdir * t * 0.35 * speed;
    h += fbm(p * 0.9 + drift, drift * 0.4) * 0.55 * (0.6 + 0.4 * min(strength, 2.0));
    // `ripple` do <Lake> — amplitude das ondas (multiplier de mundo).
    return h * CFG_WAVE_AMP;
}

/// Normal por diferenças centrais. `damp` desliga progressivamente a onda com
/// a distância — sem isso as cristas ficam mais finas que o pixel ao longe e
/// o specular cintila (aliasing) numa malha regular.
fn wave_normal(p: vec2<f32>, t: f32, damp: f32) -> vec3<f32> {
    let e = 0.28;
    let hl = wave_height(p - vec2(e, 0.0), t);
    let hr = wave_height(p + vec2(e, 0.0), t);
    let hd = wave_height(p - vec2(0.0, e), t);
    let hu = wave_height(p + vec2(0.0, e), t);
    let gain = (0.55 + 0.30 * clamp(CFG_WIND_STRENGTH, 0.0, 2.0)) * damp * CFG_WAVE_AMP;
    return normalize(vec3<f32>((hl - hr) * gain, 2.0 * e, (hd - hu) * gain));
}

// ── Fragment ─────────────────────────────────────────────────────────
@fragment
fn fragment(
    in: VertexOutput,
    @builtin(front_facing) is_front: bool,
) -> FragmentOutput {
    var pbr_input = pbr_input_from_standard_material(in, is_front);

    let t = globals.time;
    let world = pbr_input.world_position.xyz;
    // Contrato da malha: alpha = máscara de margem, uv.x = `opacity` do corpo.
    let mask = pbr_input.material.base_color.a;
#ifdef VERTEX_UVS_A
    let murk = clamp(in.uv.x, 0.05, 1.0);
#else
    let murk = 0.75;
#endif

    pbr_input.material.base_color = alpha_discard(pbr_input.material, pbr_input.material.base_color);

    let cam_dist = length(view.world_position - world);
    let damp = 1.0 / (1.0 + cam_dist * 0.010);

    // Animated surface: perturb the geometric normal towards the wave field.
    let n = wave_normal(world.xz, t, damp);
    // Seen from below keep the flipped geometric normal (front_facing path
    // already normalized it); from above blend in the waves.
    pbr_input.N = select(pbr_input.N, normalize(mix(pbr_input.N, n, 0.85)), is_front);

    // ── Coluna de água (depth prepass) ───────────────────────────────
    // `path` = caminho óptico dentro da água (absorção), `depth_v` = altura
    // real da coluna (espuma/margem). Sem prepass caímos num valor fixo que
    // mantém o corpo opaco em vez de voltar ao vidro transparente.
    // Fallback sem prepass (`VIBER_NO_POSTFX=1`): uma coluna média constante
    // — corpo sólido com o fade da malha na margem, em vez de 60 m opacos.
    var path = 2.2;
    var depth_v = 2.2;
#ifdef DEPTH_PREPASS
    let raw = prepass_utils::prepass_depth(in.position, 0u);
    if (raw > 0.0) {
        let ndc = vt::frag_coord_to_ndc(in.position);
        let scene_view = vt::position_ndc_to_view(vec3<f32>(ndc.xy, raw));
        let scene_world = (view.world_from_view * vec4<f32>(scene_view, 1.0)).xyz;
        path = clamp(distance(scene_world, world), 0.0, MAX_PATH);
        depth_v = max(world.y - scene_world.y, 0.0);
    }
#endif

    let ext = EXTINCTION * (0.45 + 1.55 * murk);
    let transmit = exp(-path * ext);
    let absorb = clamp(1.0 - dot(transmit, vec3<f32>(1.0 / 3.0)), 0.0, 1.0);
    // Margem: a lâmina nasce da profundidade, não de um anel de vértices —
    // é isto que substitui o contorno duro do disco sobre o banco.
    let shore = smoothstep(0.0, SHORE_FADE, depth_v);

    // Day clock → sun/moon direction and daylight factor (mirrors worldsys).
    var minute = CFG_CLOCK_START;
    if (CFG_DRIVE > 0.5) {
        minute = (CFG_CLOCK_START + CFG_CLOCK_SPEED * t) % 1440.0;
    }
    let day = clamp((minute - (CFG_DAWN - 60.0)) / 60.0, 0.0, 1.0)
        * (1.0 - clamp((minute - CFG_DUSK) / 60.0, 0.0, 1.0));
    let sun_el = sun_elevation_deg(minute, CFG_DAWN, CFG_DUSK, CFG_MAX_ELEV);
    let sun_az = sun_azimuth_deg(minute, CFG_DAWN, CFG_DUSK, CFG_AZ_BASE);
    // The directional light parks at min elevation during the day arc and at
    // the moon (opposite azimuth) at night — mirror `sun_drive` for the glint.
    var glint_dir = sky_direction(CFG_SUN_ELEV, CFG_SUN_AZ);
    var glint_color = vec3<f32>(1.0, 0.95, 0.85);
    var glint_strength = 1.0;
    if (CFG_DRIVE > 0.5) {
        let sun_world = sky_direction(max(sun_el, CFG_MIN_ELEV), sun_az);
        let moon_world = sky_direction(MOON_ELEVATION_DEG, sun_az + 180.0);
        glint_dir = normalize(mix(moon_world, sun_world, day));
        glint_color = mix(vec3<f32>(0.40, 0.54, 0.86), vec3<f32>(1.0, 0.95, 0.85), day);
        glint_strength = 0.22 + 0.78 * day;
    }

    // Fresnel: SEMPRE a partir de uma normal quase plana. Alimentá-lo com a
    // normal ondulada fazia a opacidade variar crista a crista — as faixas
    // rectas que se viam desenhadas por cima da relva eram exactamente isso.
    let n_flat = normalize(mix(vec3<f32>(0.0, 1.0, 0.0), pbr_input.N, 0.18));
    let nv = clamp(dot(n_flat, pbr_input.V), 0.0, 1.0);
    let fres = mix(0.02, 1.0, pow(1.0 - nv, 5.0));

    // Cheap sky reflection tint towards the horizon at grazing angles.
    let day_sky = vec3<f32>(0.36, 0.56, 0.78);
    let night_sky = vec3<f32>(0.05, 0.07, 0.13);
    let sunset = vec3<f32>(0.85, 0.45, 0.26);
    let low_sun = 1.0 - clamp(abs(sun_el) / 18.0, 0.0, 1.0);
    var sky_tint = mix(night_sky, day_sky, day);
    sky_tint = mix(sky_tint, sunset, low_sun * 0.45);

    // Espuma de margem: banda animada onde a coluna é rasa. Dá a leitura de
    // "onde a água acaba" que o fade radial da malha nunca deu.
    let foam_band = 1.0 - smoothstep(0.0, FOAM_DEPTH, depth_v);
    let foam_noise = 0.55 + 0.45 * fbm(world.xz * 1.6 + vec2(0.0, t * 0.25), vec2(t * 0.12, 0.0)) * 2.0;
    let foam = clamp(foam_band * foam_band * foam_noise, 0.0, 1.0) * shore * 0.55;

    // Corpo: cor rasa → cor profunda ao longo da absorção; o céu entra só
    // pelo fresnel, e a espuma por cima de tudo.
    let body = pbr_input.material.base_color.rgb;
    let shallow = body * 1.25;
    let deep = body * 0.42;
    var col = mix(shallow, deep, absorb);
    col += sky_tint * fres * 0.22;
    col = mix(col, vec3<f32>(0.90, 0.94, 0.95), foam);

    // Opacidade: absorção do corpo + reflexão de Fresnel por cima, tudo
    // mascarado pela margem e pelo fade da malha.
    let opacity = clamp(absorb + (1.0 - absorb) * fres, 0.0, 1.0);
    let alpha = clamp(mask * shore * max(opacity, foam), 0.0, 1.0);
    pbr_input.material.base_color = vec4<f32>(col, alpha);

    // Wave crests roughen the mirror; calmer water stays glossy.
    // Rugosidade um pouco mais alta que o espelho perfeito: a 0.06 o lóbulo
    // do sol arrastava-se pelas cristas em manchas brancas em vez de cintilar.
    pbr_input.material.perceptual_roughness = clamp(
        0.14 + 0.06 * clamp(CFG_WIND_STRENGTH, 0.0, 2.0) + 0.35 * foam,
        0.02,
        1.0,
    );

    // Sun/moon glint: tight specular lobe, masked by sparkle noise so it
    // shimmers instead of forming one perfect blob. Emissive drives bloom.
    let reflect_dir = reflect(-glint_dir, pbr_input.N);
    let lobe = pow(max(dot(reflect_dir, pbr_input.V), 0.0), 360.0);
    // Ruído de cintilação a frequência alta (célula ~11 cm): a 5.5 as células
    // eram maiores que o lóbulo e o glint saía em manchas brancas contínuas.
    let sparkle = pow(value_noise(world.xz * 9.0 + normalize(vec2<f32>(CFG_WIND_X, CFG_WIND_Z)) * t * 2.1), 3.0);
    let glint = lobe * sparkle * 1.3 * glint_strength * glint_color * damp * (1.0 - foam);
    pbr_input.material.emissive = vec4<f32>(glint, 1.0);

    var out: FragmentOutput;
    out.color = apply_pbr_lighting(pbr_input);
    out.color = main_pass_post_lighting_processing(pbr_input, out.color);
    return out;
}
